#include "levels/castle_courtyard/areas/1/1/model.inc.c"
#include "levels/castle_courtyard/areas/1/spire/model.inc.c"
#include "levels/castle_courtyard/areas/1/2/model.inc.c"
#include "levels/castle_courtyard/areas/1/3/model.inc.c"
#include "levels/castle_courtyard/areas/1/collision.inc.c"
