COURSE_ACTS(COURSE_BOB, "BATAILLE DE BOB-OMB",
       "ROI BOB-OMB DU SOMMET"         , "COURSE CONTRE KOOPA-RAPIDO"    , "CANON VERS L'ÎLE PERCHÉE",
       "LES 8 PIÈCES ROUGES"           , "VOL DU MARIO AILÉ"             , "DERRIÈRE LA CAGE DE CHOMP")

COURSE_ACTS(COURSE_WF, "FORTERESSE DE WHOMP",
       "DESTRUCTION DU GROS WHOMP"     , "EN HAUT DE LA FORTERESSE"      , "CANON VERS LES CIEUX",
       "PIÈCES ROUGES DANS LES AIRS"   , "TOMBEZ DANS LA CAGE PERCHÉE"   , "CANON VERS UN MUR...")

COURSE_ACTS(COURSE_JRB, "BAIE DES PIRATES",
       "PILLEZ LE BATEAU COULÉ"        , "L'ANGUILLE VEUT FAIRE JOUJOU?" , "TRÉSOR DANS LA CAVERNE",
       "PIÈCES ROUGES À BORD!"         , "CANON VERS LES PILIERS"        , "DANS LE GEYSER")

COURSE_ACTS(COURSE_CCM, "MONTAGNE GLA-GLA",
       "GLISSADE SUR GLACE"            , "PETIT PINGOUIN PERDU"          , "COURSE DU PINGOUIN",
       "8 PIÈCES ROUGES GIVRÉES"       , "BONHOMME DE NEIGE SANS TÊTE"   , "MURS POUR REBONDIR")

COURSE_ACTS(COURSE_BBH, "MANOIR DE BIG BOO",
       "CHERCHEZ LE BIG BOO"           , "MANÈGE DES BOOS PAS BEAUX"     , "SECRET DES LIVRES HANTÉS",
       "TROUVEZ LES 8 PIÈCES ROUGES"   , "BALCON DE BIG BOO"             , "UN OEIL SUR LES SALLES SECRÈTES")

COURSE_ACTS(COURSE_HMC, "CAVERNE BRUMEUSE",
       "GROS BIBI DE LA CAVERNE"       , "CHARIOT POUR PIÈCES ROUGES"    , "COURSE DE MÉTAL MARIO",
       "DANS LE LABYRINTHE TOXIQUE"    , "AU-DESSUS DES GAZ..."          , "ATTENTION AUX BOULETS")

COURSE_ACTS(COURSE_LLL, "LAVES FATALES",
       "CRAMEZ LE GROS MOCHE"          , "POUSSEZ LES PETITS MOCHES"     , "PUZZLE DE 8 PIÈCES ROUGES",
       "BALADE SUR LA BÛCHE"           , "CHAUD DANS LE VOLCAN"          , "ASCENCEUR DANS LE VOLCAN")

COURSE_ACTS(COURSE_SSL, "SABLES TROP MOUVANTS",
       "DANS LES GRIFFES DU VAUTOUR"   , "AU SOMMET DE LA PYRAMIDE"      , "DANS L'ANCIENNE PYRAMIDE",
       "LES QUATRE PILIERS DE LA FOI"  , "VOL VERS LES PIÈCES ROUGES"    , "ÉNIGME DE LA PYRAMIDE")

COURSE_ACTS(COURSE_DDD, "AFFREUX BASSIN",
       "SOUS-MARIN DE BOWSER"          , "COFFRES DANS LE COURANT"       , "PERCHES POUR PIÈCES ROUGES",
       "DANS LE GEYSER"                , "RÉCOMPENSE DE LA RAIE"         , "ASSOCIATION DE CASQUETTES...")

COURSE_ACTS(COURSE_SL, "CHEZ LE ROI DES NEIGES",
       "GROSSE TÊTE DU BONHOMME"       , "COMBATTEZ LE GROS MOCHE GIVRÉ" , "DANS LE GLAÇON",
       "VRILLE DEPUIS LE LAC"          , "CARAPACE POUR PIÈCES ROUGES"   , "DANS L'IGLOO")

COURSE_ACTS(COURSE_WDW, "MONDE TREMPE-SECHE",
       "MINI PLATES-FORMES FLÉCHÉES!"  , "SUR LES TOITS"                 , "ÉNIGME DES CHIFFRES CACHÉS",
       "ASCENSEUR EXPRESS!"            , "PIÈCES ROUGES: VILLE ENGLOUTIE", "COURSE EN VILLE")

COURSE_ACTS(COURSE_TTM, "TROP HAUTE MONTAGNE",
       "ESCALADEZ LA MONTAGNE"         , "MYSTÈRE DE LA CAGE DU SINGE"   , "PIÈCES ROUGES SUR CHAMPIGNON",
       "PAROI MYSTÉRIEUSE"             , "PANORAMA DU PONT"              , "CANON VERS LE CHAMPIGNON")

COURSE_ACTS(COURSE_THI, "ÎLE GRANDS-PETITS",
       "DÉTRUISEZ LES MAXI-CARNIVORES" , "AU SOMMET DE L'ÎLE DES GÉANTS" , "KOOPA-RAPIDO, LA VENGEANCE",
       "CINQ TOUT PETITS SECRETS"      , "LES PIÈCES ROUGES DU GIGOTEUR" , "ÉNERVEZ LE GIGOTEUR")

COURSE_ACTS(COURSE_TTC, "HORLOGE TIC-TAC",
       "ROULEMENTS DANS LA CAGE"       , "LES TROUS ET LE PENDULE"       , "CHEVAUCHEZ L'AIGUILLE",
       "L'ÉCRABOUILLEUR"               , "SAUTS SYNCHRONISÉS"            , "L'HEURE PILE POUR LES PIÈCES")

COURSE_ACTS(COURSE_RR, "COURSE ARC-EN-CIEL",
       "CROISIÈRE SUR L'ARC-EN-CIEL"   , "MANOIR DANS LES AIRS"          , "LABYRINTHE DES PIÈCES ROUGES",
       "BALANÇOIRE CÉLESTE"            , "VICIEUX TRIANGLES!"            , "L'ARC-EN-CIEL ET AU-DELÀ")

SECRET_STAR(COURSE_BITDW, "BOWSER DES TÉNÈBRES")
SECRET_STAR(COURSE_BITFS, "BOWSER DES LAVES")
SECRET_STAR(COURSE_BITS, "BOWSER DES CIEUX")
SECRET_STAR(COURSE_PSS, "GLISSADE DE LA PRINCESSE")
SECRET_STAR(COURSE_COTMC, "MINE DES CASQUETTES-MÉTAL")
SECRET_STAR(COURSE_TOTWC, "INTERRUPTEUR DE LA TOUR AILÉE")
SECRET_STAR(COURSE_VCUTM, "INVISIBLE SOUS LES DOUVES")
SECRET_STAR(COURSE_WMOTR, "AU-DELÀ DE L'ARC-EN-CIEL")
SECRET_STAR(COURSE_SA, "AQUARIUM SECRET")
SECRET_STAR(COURSE_CAKE_END, "")

CASTLE_SECRET_STARS("ÉTOILES SECRÈTES")

EXTRA_TEXT(0, "UNE ÉTOILE SECRÈTE DU CHÂTEAU")
EXTRA_TEXT(1, "")
EXTRA_TEXT(2, "")
EXTRA_TEXT(3, "")
EXTRA_TEXT(4, "")
EXTRA_TEXT(5, "")
EXTRA_TEXT(6, "")
