COURSE_ACTS(COURSE_BOB, " 1 BATAILLE DE BOB-OMB",
       "ROI BOB-OMB DU SOMMET"         , "COURSE CONTRE KOOPA-RAPIDO"    , "CANON VERS L'ILE PERCHEE",
       "LES 8 PIECES ROUGES"           , "VOL DU MARIO AILE"             , "DERRIERE LA CAGE DE CHOMP")

COURSE_ACTS(COURSE_WF, " 2 FORTERESSE DE WHOMP",
       "DESTRUCTION DU GROS WHOMP"     , "EN HAUT DE LA FORTERESSE"      , "CANON VERS LES CIEUX",
       "PIECES ROUGES DANS LES AIRS"   , "TOMBEZ DANS LA CAGE PERCHEE"   , "CANON VERS UN MUR...")

COURSE_ACTS(COURSE_JRB, " 3 BAIE DES PIRATES",
       "PILLEZ LE BATEAU COULE"        , "L'ANGUILLE VEUT FAIRE JOUJOU?" , "TRESOR DANS LA CAVERNE",
       "PIECES ROUGES A BORD!"         , "CANON VERS LES PILIERS"        , "DANS LE GEYSER")

COURSE_ACTS(COURSE_CCM, " 4 MONTAGNE GLA-GLA",
       "GLISSADE SUR GLACE"            , "PETIT PINGOUIN PERDU"          , "COURSE DU PINGOUIN",
       "8 PIECES ROUGES GIVREES"       , "BONHOMME DE NEIGE SANS TETE"   , "MURS POUR REBONDIR")

COURSE_ACTS(COURSE_BBH, " 5 MANOIR DE BIG BOO",
       "CHERCHEZ LE BIG BOO"           , "MANEGE DES BOOS PAS BEAUX"     , "SECRET DES LIVRES HANTES",
       "TROUVEZ LES 8 PIECES ROUGES"   , "BALCON DE BIG BOO"             , "UN OEIL SUR LES SALLES SECRETES")

COURSE_ACTS(COURSE_HMC, " 6 CAVERNE BRUMEUSE",
       "GROS BIBI DE LA CAVERNE"       , "CHARIOT POUR PIECES ROUGES"    , "COURSE DE METAL MARIO",
       "DANS LE LABYRINTHE TOXIQUE"    , "AU-DESSUS DES GAZ..."          , "ATTENTION AUX BOULETS")

COURSE_ACTS(COURSE_LLL, " 7 LAVES FATALES",
       "CRAMEZ LE GROS MOCHE"          , "POUSSEZ LES PETITS MOCHES"     , "PUZZLE DE 8 PIECES ROUGES",
       "BALADE SUR LA BUCHE"           , "CHAUD DANS LE VOLCAN"          , "ASCENCEUR DANS LE VOLCAN")

COURSE_ACTS(COURSE_SSL, " 8 SABLES TROP MOUVANTS",
       "DANS LES GRIFFES DU VAUTOUR"   , "AU SOMMET DE LA PYRAMIDE"      , "DANS L'ANCIENNE PYRAMIDE",
       "LES QUATRE PILIERS DE LA FOI"  , "VOL VERS LES PIECES ROUGES"    , "ENIGME DE LA PYRAMIDE")

COURSE_ACTS(COURSE_DDD, " 9 AFFREUX BASSIN",
       "SOUS-MARIN DE BOWSER"          , "COFFRES DANS LE COURANT"       , "PERCHES POUR PIECES ROUGES",
       "DANS LE GEYSER"                , "RECOMPENSE DE LA RAIE"         , "ASSOCIATION DE CASQUETTES...")

COURSE_ACTS(COURSE_SL, "10 CHEZ LE ROI DES NEIGES",
       "GROSSE TETE DU BONHOMME"       , "COMBATTEZ LE GROS MOCHE GIVRE" , "DANS LE GLAÇON",
       "VRILLE DEPUIS LE LAC"          , "CARAPACE POUR PIECES ROUGES"   , "DANS L'IGLOO")

COURSE_ACTS(COURSE_WDW, "11 MONDE TREMPE-SECHE",
       "MINI PLATES-FORMES FLECHEES!"  , "SUR LES TOITS"                 , "ENIGME DES CHIFFRES CACHES",
       "ASCENSEUR EXPRESS!"            , "PIECES ROUGES: VILLE ENGLOUTIE", "COURSE EN VILLE")

COURSE_ACTS(COURSE_TTM, "12 TROP HAUTE MONTAGNE",
       "ESCALADEZ LA MONTAGNE"         , "MYSTERE DE LA CAGE DU SINGE"   , "PIECES ROUGES SUR CHAMPIGNON",
       "PAROI MYSTERIEUSE"             , "PANORAMA DU PONT"              , "CANON VERS LE CHAMPIGNON")

COURSE_ACTS(COURSE_THI, "13 ILE GRANDS-PETITS",
       "DETRUISEZ LES MAXI-CARNIVORES" , "AU SOMMET DE L'ILE DES GEANTS" , "KOOPA-RAPIDO, LA VENGEANCE",
       "CINQ TOUT PETITS SECRETS"      , "LES PIECES ROUGES DU GIGOTEUR" , "ENERVEZ LE GIGOTEUR")

COURSE_ACTS(COURSE_TTC, "14 HORLOGE TIC-TAC",
       "ROULEMENTS DANS LA CAGE"       , "LES TROUS ET LE PENDULE"       , "CHEVAUCHEZ L'AIGUILLE",
       "L'ECRABOUILLEUR"               , "SAUTS SYNCHRONISES"            , "L'HEURE PILE POUR LES PIECES")

COURSE_ACTS(COURSE_RR, "15 COURSE ARC-EN-CIEL",
       "CROISIERE SUR L'ARC-EN-CIEL"   , "MANOIR DANS LES AIRS"          , "LABYRINTHE DES PIECES ROUGES",
       "BALANÇOIRE CELESTE"            , "VICIEUX TRIANGLES!"            , "L'ARC-EN-CIEL ET AU-DELA")

SECRET_STAR(COURSE_BITDW, "   BOWSER DES TENEBRES")
SECRET_STAR(COURSE_BITFS, "   BOWSER DES LAVES")
SECRET_STAR(COURSE_BITS, "   BOWSER DES CIEUX")
SECRET_STAR(COURSE_PSS, "   GLISSADE DE LA PRINCESSE")
SECRET_STAR(COURSE_COTMC, "   MINE DES CASQUETTES-METAL")
SECRET_STAR(COURSE_TOTWC, "   INTERRUPTEUR DE LA TOUR AILEE")
SECRET_STAR(COURSE_VCUTM, "   INVISIBLE SOUS LES DOUVES")
SECRET_STAR(COURSE_WMOTR, "   AU-DELA DE L'ARC-EN-CIEL")
SECRET_STAR(COURSE_SA, "   AQUARIUM SECRET")
SECRET_STAR(COURSE_CAKE_END, "")

CASTLE_SECRET_STARS("   ETOILES SECRETES")

EXTRA_TEXT(0, "UNE ETOILE SECRETE DU CHATEAU")
EXTRA_TEXT(1, "")
EXTRA_TEXT(2, "")
EXTRA_TEXT(3, "")
EXTRA_TEXT(4, "")
EXTRA_TEXT(5, "")
EXTRA_TEXT(6, "")
