COURSE_ACTS(COURSE_BOB, "FRENTE BOB-OMB",
       "REY BOB-OMB EN LA CIMA"     , "CARRERA CON KOOPA EL RÁPIDO" , "CAÑONAZO A LA ISLA EN EL CIELO",
       "ENCUENTRA LAS 8 MONEDAS ROJAS"          , "MARIO ALADO POR EL CIELO"        , "TRAS LAS REJAS DE CHOMP CADENAS")

COURSE_ACTS(COURSE_WF, " FORTALEZA ROCO",
       "DERROTA AL REY ROCO"        , "EN LO MÁS ALTO DE LA FORTALEZA"    , "CAÑONAZO AL CIELO",
       "MONEDAS ROJAS EN LA ISLA FLOANTE", "CAE EN LA ISLA ENJAULADA"    , "REVIENTA LA PARED")

COURSE_ACTS(COURSE_JRB, "BAHÍA PIRATA",
       "SAQUEA EL BARCO HUNDIDO"    , "¿PUEDE SALIR LA ANGUILA A JUGAR?" , "TESORO DE LA CUEVA DEL OCÉANO",
       "MONEDAS ROJAS EN EL BARCO FLOTANTE"  , "CAÑONAZO AL PILAR DE PIEDRA"     , "A CONTRACORRIENTE")

COURSE_ACTS(COURSE_CCM, "MONTAÑA HELADA",
       "RESBÁLATE Y DESLÍZATE"             , "PEQUEÑO PINGÜINO PERDIDO"             , "CARRERA CONTRA EL GRAN PINGÜINO",
       "MONEDAS ROJAS EN EL TOBOGÁN REFRESCANTE"  , "EL MUÑECO DE NIEVE HA PERDIDO LA CABEZA"       , "LOS SALTOS EN PARED TE SERVIRÁN")

COURSE_ACTS(COURSE_BBH, "GRAN SUSTO BOO",
       "CAZAFANTASMAS"            , "SUBE AL TIOVIVO DEL GRAN BOO" , "SECRETO DE LOS LIBROS ENCANTADOS",
       "BUSCA LAS 8 MONEDAS ROJAS"          , "EL BALCÓN DEL GRAN BOO"             , "OJO POR OJO EN LA SALA OCULTA")

COURSE_ACTS(COURSE_HMC, "CUEVA LABERÍNTICA",
       "MONSTRUO NADADOR EN LA CAVERNA"  , "ELÉVATE A POR LAS 8 MONEDAS"       , "¡MARIO METALERO SE MUEVE!",
       "NAVEGA EL LABERINTO TÓXICO"     , "SALIDA DE EMERGENCIA DEL LABERINTO"     , "PELIGRO DE DESPRENDIMIENTO")

COURSE_ACTS(COURSE_LLL, "TIERRA DE LAVA LETAL",
       "HIERVE AL GRAN BULLY"            , "HAZLE BULLYING A LOS BULLIES"             , "8 MONEDAS ROJAS, 15 PIEZAS DE PUZZLE",
       "TRONCO ARDIENTE Y RODANTE"           , "DE CABEZA AL VOLCÁN"  , "TOUR DE ASCENSORES EN EL VOLCÁN")

COURSE_ACTS(COURSE_SSL, "ARENAS CAMBIANTES",
       "EN LOS TALONES DE LA GRAN AVE" , "RELUCE EN LO ALTO DE LA PIRÁMIDE"      , "DENTRO DE LA ANTIGUA PIRÁMIDE",
       "PISA LOS CUATRO PILARES", "VUELO LIBRE POR 8 MONEDAS ROJAS"   , "PUZZLE PIRAMIDAL")

COURSE_ACTS(COURSE_DDD, "MUELLE DESOLADO",
       "INVADE EL SUBMARINO DE BOWSER"            , "COFRES EN LA CORRIENTE"         , "MONEDAS ROJAS DE PALO EN PALO",
       "A CONTRACORRIENTE"        , "LA RECOMPENSA DE LA MANTA"        , "CONSIGUE LAS GORRAS...")

COURSE_ACTS(COURSE_SL, "PAÍS MUÑECO DE NIEVE",
       "EL CABEZÓN DEL MUÑECO DE NIEVE"            , "REFRÉSCATE CON EL BULLY"          , "CONGELAMIENTO PROFUNDO",
       "TORBELLINO DESDE EL LAGO HELADO"  , "8 MONEDAS ROJAS EN CAPARAZÓN" , "DENTRO DEL IGLÚ")

COURSE_ACTS(COURSE_WDW, "MUNDO MOJASECA",
       "¡ASCENSORES ELECTRIFICANTES!"         , "EN LO ALTO DEL PUEBLO"               , "SECRETOS EN LOS HUECOS Y EL CIELO",
       "ASCENSOR EXPRESS - ¡DATE PRISA!"   , "VETE AL PUEBLO A POR MONEDAS ROJAS"      , "¡A TODA PRISA POR EL PUEBLO!")

COURSE_ACTS(COURSE_TTM, "MONTAÑA SUBE-SUBE",
       "ESCALA LA MONTAÑA"            , "EL MISTERIO DE LA JAULA DEL MONO"    , "CHAMPIÑONES ESCALOFRIANTES, MONEDAS ROJAS",
       "EL LADO MISTERIOSO DE LA MONTAÑA"       , "VISTA INCREÍBLE DESDE EL PUENTE" , "CAÑONAZO AL CHAMPIÑÓN SOLITARIO")

COURSE_ACTS(COURSE_THI, "ISLA CAMBIANTE",
       "ARRANCA LA PLANTA PIRAÑA"      , "LA CIMA DE LA ISLA GIGANTE", "REVANCHA DE KOOPA EL RÁPIDO",
       "CINCO SECRETITOS DE NADA"       , "LAS MONEDAS ROJAS DE WIGGLER"           , "HAZ QUE WIGGLER SE RETUERZA")

COURSE_ACTS(COURSE_TTC, "RELOJ TIC TAC",
       "SALTA A LA JAULA"            , "EL VACÍO Y LOS PÉNDULOS"     , "¿TE ECHO UNA MANECILLA?",
       "PISOTEA AL THWOMP"           , "SALTOS PRECISOS EN LAS BARRAS"    , "PARA EL TIEMPO, CONSIGUE MONEDAS ROJAS")

COURSE_ACTS(COURSE_RR, "CAMINO DEL ARCOÍRIS",
       "CRUCERO POR EL ARCOÍRIS"  , "LA GRAN CASA EN EL CIELO"      , "MONEDAS EN EL LABERINTO",
       "SALTANDO POR LAS CORRIENTES"        , "¡TRIÁNGULOS CON TRUCO!"             , "POR ENCIMA DEL ARCOÍRIS")

SECRET_STAR(COURSE_BITDW, "BOWSER EN EL MUNDO OSCURO")
SECRET_STAR(COURSE_BITFS, "BOWSER EN EL MAR DE FUEGO")
SECRET_STAR(COURSE_BITS, "BOWSER EN EL CIELO")
SECRET_STAR(COURSE_PSS, "EL TOBOGÁN SECRETO DE LA PRINCESA")
SECRET_STAR(COURSE_COTMC, "CAVERNA DE LA GORRA DE METAL")
SECRET_STAR(COURSE_TOTWC, "TORRE DE LA GORRA VOLADORA")
SECRET_STAR(COURSE_VCUTM, "FOSO DE LA GORRA DE INVISIBILIDAD")
SECRET_STAR(COURSE_WMOTR, "MARIO ALADO SOBRE EL ARCOÍRIS")
SECRET_STAR(COURSE_SA, "EL ACUARIO SECRETO")
SECRET_STAR(COURSE_CAKE_END, "")

CASTLE_SECRET_STARS("ESTRELLAS SECRETAS")

EXTRA_TEXT(0, "¡UNA DE LAS ESTRELLAS SECRETAS!")
EXTRA_TEXT(1, "")
EXTRA_TEXT(2, "")
EXTRA_TEXT(3, "")
EXTRA_TEXT(4, "")
EXTRA_TEXT(5, "")
EXTRA_TEXT(6, "")
