COURSE_ACTS(COURSE_BOB, "BOB-OMBS BOMBENBERG",
       "BESIEGE KÖNIG BOB-OMB!"        , "BESIEGE DEN SCHNELLEN KOOPA!"  , "FLIEGE ZUR SCHWEBENDEN INSEL!",
       "FINDE DIE 8 ROTEN MÜNZEN!"     , "DURCHFLIEGE ALLE MÜNZENRINGE!" , "BEFREIE DEN KETTENHUND!")

COURSE_ACTS(COURSE_WF, "WUMMPS WUCHTWALL",
       "BESIEGE KÖNIG WUMMP!"          , "STEIGE AUF DIE BERGFESTUNG!"   , "FLIEG INS BLAUE!",
       "FINDE DIE 8 ROTEN MÜNZEN!"     , "WECKE DIE EULE!"               , "ZERSTÖRE DIE FELSWAND!")

COURSE_ACTS(COURSE_JRB, "PIRATENBUCHT PANIK",
       "TAUCHE IN DAS SCHIFFSWRACK!"   , "LOCKE DEN AAL KANO HERAUS!"    , "TAUCHE ZUR SCHATZHÖHLE!",
       "FINDE DIE 8 ROTEN MÜNZEN!"     , "FLIEGE ZU DEN STEINSÄULEN!"    , "LAUFE DURCH DEN STRUDEL!")

COURSE_ACTS(COURSE_CCM, "BIBBERBERG BOB",
       "RUTSCHE AUF DER EISBAHN!"      , "FINDE DAS PINGUINBABY!"        , "BESIEGE DEN SCHNELLEN PINGUIN!",
       "FINDE DIE 8 ROTEN MÜNZEN!"     , "BAUE EINEN SCHNEEMANN!"        , "DENKE AN DEN WANDSPRUNG!")

COURSE_ACTS(COURSE_BBH, "BIG BOOS BURG",
       "GEHE AUF GEISTERJAGD!"         , "BESUCHE BIG BOOS KARUSSEL!"    , "LÖSE DAS BÜCHEREI-RÄTSEL!",
       "FINDE DIE 8 ROTEN MÜNZEN!"     , "KLETTERE AUF BIG BOOS BALKON!" , "FINDE DAS AUGE IM GEHEIMRAUM!")

COURSE_ACTS(COURSE_HMC, "GRÜNE GIFTGROTTE",
       "KLETTERE AUF NESSIS RÜCKEN!"   , "FINDE DIE 8 ROTEN MÜNZEN!"     , "LAUFE AUF DEM GRUND DES SEES!",
       "DURCHSUCHE DAS NEBELLABYRINTH!", "SUCHE IM NEBEL DEN NOTAUSGANG!", "ACHTE AUF ROLLENDE FELSEN!")

COURSE_ACTS(COURSE_LLL, "LAVA LAGUNE",
       "WERFE BIG BULLY IN DIE LAVA!"  , "WERFE DIE BULLIES IN DIE LAVA!", "FINDE DIE 8 ROTEN MÜNZEN!",
       "TANZE AUF DEM BAUMSTAMM!"      , "ERKUNDE DEN VULKAN!"           , "GEWINNE IM VULKAN AN HÖHE!")

COURSE_ACTS(COURSE_SSL, "WOBIWABA WÜSTE",
       "FOLGE DEM RIESENGEIER!"        , "BRINGE LICHT IN DIE PYRAMIDE!" , "BEGEBE DICH IN DIE PYRAMIDE!",
       "LANDE AUF ALLEN VIER SÄULEN!"  , "FINDE DIE 8 ROTEN MÜNZEN!"     , "LÖSE DAS PYRAMIDENPUZZLE!")

COURSE_ACTS(COURSE_DDD, "WILDE WASSERWERFT",
       "ENTERE BOWSERS U-BOOT!"        , "ÖFFNE DIE TRUHEN!"             , "SPRINGE ZU DEN ROTEN MÜNZEN!",
       "SCHWIMME DURCH DIE RINGE!"     , "FOLGE DEM FISCH!"              , "VEREINE DIE MÜTZEN!")

COURSE_ACTS(COURSE_SL, "FROSTBEULEN FRUST",
       "ERKLIMME DEN KOPF!"            , "SPIELE MIT BAD BULLY!"         , "WAGE DICH INS EIS!",
       "GEHE ZUM EISSEE!"              , "FINDE DIE 8 ROTEN MÜNZEN!"     , "SCHAU IM IGLU NACH!")

COURSE_ACTS(COURSE_WDW, "ATLANTIS AQUARIA",
       "FOLGE DEN BLAUEN PFEILEN!"     , "SUCHE NACH DER SPITZE DER STADT!", "ERFORSCHE DIE HÖHEN UND TIEFEN!",
       "BEEILE DICH - EXPRESSAUFZUG!"  , "FINDE DIE 8 ROTEN MÜNZEN!"     , "BEACHTE DAS ZEITLIMIT!")

COURSE_ACTS(COURSE_TTM, "FLIEGENPILZ FIASKO",
       "ERKLIMME DEN BERG!"            , "ERKUNDE DEN AFFENKÄFIG!"       , "FINDE DIE 8 ROTEN MÜNZEN!",
       "ERFORSCHE DIE STEILWAND!"      , "HALTE AUSSCHAU AUF DER BRÜCKE!", "SUCHE DEN EINSAMEN PILZ!")

COURSE_ACTS(COURSE_THI, "GULLIVER GUMBA",
       "PFLÜCKE DIE SCHNAPP-PIRANHA!"  , "BEGIB DICH ZUR SPITZE DER INSEL!", "TRETE NOCH EINMAL GEGEN KOOPA AN!",
       "LÖSE DIE 5 ITTY BITTY-RÄTSEL!" , "FINDE DIE 8 ROTEN MÜNZEN!"     , "DREHE WIGGLER IM KREIS!")

COURSE_ACTS(COURSE_TTC, "TICK TACK TRAUMA",
       "ROLLE DEN KÄFIG!"              , "ACHTE AUF DAS PENDEL!"         , "LASS DIR DEN WEG ZEIGEN!",
       "STAMPFE MÄCHTIG AUF!"          , "SPRINGE AUF DEN SCHWEBEBALKEN!", "FINDE DIE 8 ROTEN MÜNZEN!")

COURSE_ACTS(COURSE_RR, "REGENBOGEN RASEREI",
       "REISE AUF DEN REGENBÖGEN!"     , "SUCHE DAS HAUS AM HIMMEL!"     , "FINDE DIE 8 ROTEN MÜNZEN!",
       "LASS DICH VON DER BRISE TRAGEN!", "ÜBERWINDE DIE MACHT DER DREIECKE!", "SCHAU DIR DEN REGENBOGEN AN!")

SECRET_STAR(COURSE_BITDW, "BOWSERS SCHATTENWELT")
SECRET_STAR(COURSE_BITFS, "BOWSERS LAVASEE")
SECRET_STAR(COURSE_BITS, "BOWSERS LUFTSCHLOSS")
SECRET_STAR(COURSE_PSS, "TOADSTOOLS RUTSCHBAHN")
SECRET_STAR(COURSE_COTMC, "GRÜNER SCHALTERPALAST")
SECRET_STAR(COURSE_TOTWC, "ROTER SCHALTERPALAST")
SECRET_STAR(COURSE_VCUTM, "BLAUER SCHALTERPALAST")
SECRET_STAR(COURSE_WMOTR, "REGENBOGEN FEUERWERK")
SECRET_STAR(COURSE_SA, "VERSTECKTES AQUARIUM")
SECRET_STAR(COURSE_CAKE_END, "")

CASTLE_SECRET_STARS("GEHEIME STERNE")

EXTRA_TEXT(0, "EIN GEHEIMER STERN DES SCHLOSSES!")
EXTRA_TEXT(1, "")
EXTRA_TEXT(2, "")
EXTRA_TEXT(3, "")
EXTRA_TEXT(4, "")
EXTRA_TEXT(5, "")
EXTRA_TEXT(6, "")
