#include <ultra64.h>
#include "sm64.h"
#include "surface_terrains.h"
#include "moving_texture_macros.h"
#include "surface_terrains.h"
#include "textures.h"

#include "make_const_nonconst.h"

#include "actors/vanilla_actors/bits/texture.inc.c"

#include "actors/vanilla_actors/bits/20/model.inc.c"
#include "actors/vanilla_actors/bits/21/model.inc.c"
#include "actors/vanilla_actors/bits/22/model.inc.c"
#include "actors/vanilla_actors/bits/23/model.inc.c"
#include "actors/vanilla_actors/bits/24/model.inc.c"
#include "actors/vanilla_actors/bits/25/model.inc.c"
#include "actors/vanilla_actors/bits/26/model.inc.c"
#include "actors/vanilla_actors/bits/27/model.inc.c"
#include "actors/vanilla_actors/bits/28/model.inc.c"
#include "actors/vanilla_actors/bits/29/model.inc.c"
#include "actors/vanilla_actors/bits/30/model.inc.c"
#include "actors/vanilla_actors/bits/31/model.inc.c"
#include "actors/vanilla_actors/bits/32/model.inc.c"

#include "actors/vanilla_actors/bits/20/collision.inc.c"
#include "actors/vanilla_actors/bits/21/collision.inc.c"
#include "actors/vanilla_actors/bits/22/collision.inc.c"
#include "actors/vanilla_actors/bits/23/collision.inc.c"
#include "actors/vanilla_actors/bits/24/collision.inc.c"
#include "actors/vanilla_actors/bits/25/collision.inc.c"
#include "actors/vanilla_actors/bits/26/collision.inc.c"
#include "actors/vanilla_actors/bits/27/collision.inc.c"
#include "actors/vanilla_actors/bits/28/collision.inc.c"
#include "actors/vanilla_actors/bits/29/collision.inc.c"
#include "actors/vanilla_actors/bits/30/collision.inc.c"
#include "actors/vanilla_actors/bits/31/collision.inc.c"
#include "actors/vanilla_actors/bits/32/collision.inc.c"
