extern const GeoLayout rr_area_1_geo[];
extern const GeoLayout rr_area_1[];
extern const Collision rr_area_1_collision[];
extern const MacroObject rr_area_1_macro_objs[];
extern Lights1 rr_dl_sm64_material_lights;
extern Lights1 rr_dl_sm64_material_001_layer5_area1_lights;
extern u8 rr_dl_RMGP01_c307971e_14_ci4[];
extern u8 rr_dl_RMGP01_c307971e_14_ci4_pal_rgba16[];
extern u8 rr_dl_fog_ia8[];
extern Vtx rr_dl_Cube_mesh_vtx_0[56];
extern Gfx rr_dl_Cube_mesh_tri_0[];
extern Vtx rr_dl_Cube_001_mesh_vtx_0[25];
extern Gfx rr_dl_Cube_001_mesh_tri_0[];
extern Gfx mat_rr_dl_sm64_material[];
extern Gfx mat_revert_rr_dl_sm64_material[];
extern Gfx mat_rr_dl_sm64_material_001_layer5_area1[];
extern Gfx mat_revert_rr_dl_sm64_material_001_layer5_area1[];
extern Gfx rr_dl_Cube_mesh[];
extern Gfx rr_dl_Cube_001_mesh[];
extern Gfx rr_dl_material_revert_render_settings[];
