extern const GeoLayout castle_grounds_area_1_geo[];
extern const GeoLayout castle_grounds_area_1[];
extern const Collision castle_grounds_area_1_collision[];
extern const MacroObject castle_grounds_area_1_macro_objs[];
extern u8 castle_grounds_dl_stripes_i4[];
extern u8 castle_grounds_dl_checkerboard_ci4[];
extern u8 castle_grounds_dl_checkerboard_ci4_pal_rgba16[];
extern Vtx castle_grounds_dl_Column_mesh_vtx_cull[8];
extern Vtx castle_grounds_dl_Column_mesh_vtx_0[26];
extern Gfx castle_grounds_dl_Column_mesh_tri_0[];
extern Vtx castle_grounds_dl_Icosphere_mesh_vtx_cull[8];
extern Vtx castle_grounds_dl_Icosphere_mesh_vtx_0[90];
extern Gfx castle_grounds_dl_Icosphere_mesh_tri_0[];
extern Vtx castle_grounds_dl_Plane_mesh_vtx_cull[8];
extern Vtx castle_grounds_dl_Plane_mesh_vtx_0[99];
extern Gfx castle_grounds_dl_Plane_mesh_tri_0[];
extern Vtx castle_grounds_dl_Plane_mesh_vtx_1[4];
extern Gfx castle_grounds_dl_Plane_mesh_tri_1[];
extern Gfx mat_castle_grounds_dl_column_v3[];
extern Gfx mat_revert_castle_grounds_dl_column_v3[];
extern Gfx mat_castle_grounds_dl_sm64_material[];
extern Gfx mat_castle_grounds_dl_checkerboard_v3[];
extern Gfx mat_revert_castle_grounds_dl_checkerboard_v3[];
extern Gfx castle_grounds_dl_Column_mesh[];
extern Gfx castle_grounds_dl_Icosphere_mesh[];
extern Gfx castle_grounds_dl_Plane_mesh[];
extern Gfx castle_grounds_dl_material_revert_render_settings[];
