#include "levels/totwc/texture.inc.c"
#include "levels/totwc/areas/1/1/model.inc.c"
#include "levels/totwc/areas/1/2/model.inc.c"
#include "levels/totwc/areas/1/3/model.inc.c"
#include "levels/totwc/cloud/model.inc.c"
#include "levels/totwc/areas/1/collision.inc.c"
