#include <ultra64.h>
#include "sm64.h"
#include "geo_commands.h"

#include "make_const_nonconst.h"

#include "common1.h"
#include "common0.h"

#include "blue_coin_switch/geo.inc.c"
// Hmm, this is included earlier.
#include "test_platform/geo.inc.c"
#include "amp/geo.inc.c"
#include "cannon_lid/geo.inc.c"
#include "cannon_base/geo.inc.c"
#include "cannon_barrel/geo.inc.c"
#include "chuckya/geo.inc.c"
#include "purple_switch/geo.inc.c"
#include "checkerboard_platform/geo.inc.c"
#include "heart/geo.inc.c"
#include "flyguy/geo.inc.c"
#include "breakable_box/geo.inc.c"
#include "bowling_ball/geo.inc.c"
#include "exclamation_box/geo.inc.c"
#include "goomba/geo.inc.c"
#include "bobomb/geo.inc.c"
#include "metal_box/geo.inc.c"
#include "exclamation_box_outline/geo.inc.c"
#include "koopa_shell/geo.inc.c"

#include "game/farcall_helpers.h"

#include "game/behaviors/blue_coin.inc.c"
#include "game/behaviors/amp.inc.c"
#include "game/behaviors/cannon_door.inc.c"
#include "game/behaviors/cannon.inc.c"
#include "game/behaviors/switch_hidden_objects.inc.c"
#include "game/behaviors/breakable_box.inc.c"
#include "game/behaviors/breakable_box_small.inc.c"
#include "game/behaviors/recovery_heart.inc.c"
#include "game/behaviors/purple_switch.inc.c"
#include "game/behaviors/checkerboard_platform.inc.c"
#include "game/behaviors/bowling_ball.inc.c"
#include "game/behaviors/exclamation_box.inc.c"
#include "game/behaviors/koopa_shell.inc.c"
#include "game/behaviors/koopa_shell_underwater.inc.c"
#include "game/behaviors/corkbox.inc.c"
#include "game/behaviors/unused_poundable_platform.inc.c"
#include "game/behaviors/jumping_box.inc.c"
#include "game/behaviors/fly_guy.inc.c"
#include "game/behaviors/fire_spitter.inc.c"
#include "game/behaviors/chuckya.inc.c"
#include "game/behaviors/bobomb.inc.c"
#include "game/behaviors/metal_box.inc.c"
#include "game/behaviors/goomba.inc.c"

