#include <ultra64.h>
#include "sm64.h"
#include "geo_commands.h"

#include "make_const_nonconst.h"

#include "common1.h"
#include "group0.h"

#include "bubble/geo.inc.c"
#include "walk_smoke/geo.inc.c"
#include "burn_smoke/geo.inc.c"
#include "small_water_splash/geo.inc.c"
#include "water_wave/geo.inc.c"
#include "sparkle/geo.inc.c"
#include "water_splash/geo.inc.c"
#include "sparkle_animation/geo.inc.c"
#include "mario/geo.inc.c"

#include "physcube/geo.inc.c"
#include "physsphere/geo.inc.c"
#include "m_body/geo.inc.c"
#include "m_head/geo.inc.c"
#include "m_shoulder_l/geo.inc.c"
#include "m_shoulder_r/geo.inc.c"
#include "m_arm_l/geo.inc.c"
#include "m_arm_r/geo.inc.c"
#include "m_hand_l/geo.inc.c"
#include "m_hand_r/geo.inc.c"
#include "m_thigh_l/geo.inc.c"
#include "m_thigh_r/geo.inc.c"
#include "m_leg_l/geo.inc.c"
#include "m_leg_r/geo.inc.c"
#include "m_foot_l/geo.inc.c"
#include "m_foot_r/geo.inc.c"
