#ifndef GROUP0_H
#define GROUP0_H

#include "types.h"

// bubble
extern const GeoLayout bubble_geo[];
extern const GeoLayout purple_marble_geo[];
extern const Gfx bubble_seg4_dl_0401DD60[];
extern const Gfx bubble_seg4_dl_0401DDE0[];

// burn_smoke
extern const GeoLayout burn_smoke_geo[];
extern const Gfx burn_smoke_seg4_sub_dl_begin[];
extern const Gfx burn_smoke_seg4_sub_dl_model[];
extern const Gfx burn_smoke_seg4_sub_dl_end[];
extern const Gfx burn_smoke_seg4_dl[];

// mario
extern const GeoLayout mario_geo_face_and_wings[];
extern const GeoLayout mario_geo_left_hand[];
extern const GeoLayout mario_geo_right_hand[];
extern const GeoLayout mario_geo_body[];
extern const GeoLayout mario_geo_medium_poly_left_hand[];
extern const GeoLayout mario_geo_medium_poly_right_hand[];
extern const GeoLayout mario_geo_medium_poly_body[];
extern const GeoLayout mario_geo_low_poly_face_and_wings[];
extern const GeoLayout mario_geo_low_poly_left_hand[];
extern const GeoLayout mario_geo_low_poly_right_hand[];
extern const GeoLayout mario_geo_low_poly_body[];
extern const GeoLayout mario_vanish_geo_face_and_wings[];
extern const GeoLayout mario_vanish_geo_left_hand[];
extern const GeoLayout mario_vanish_geo_right_hand[];
extern const GeoLayout mario_vanish_geo_body[];
extern const GeoLayout mario_vanish_geo_medium_poly_left_hand[];
extern const GeoLayout mario_vanish_geo_medium_poly_right_hand[];
extern const GeoLayout mario_vanish_geo_medium_poly_body[];
extern const GeoLayout mario_vanish_geo_low_poly_face_and_wings[];
extern const GeoLayout mario_vanish_geo_low_poly_left_hand[];
extern const GeoLayout mario_vanish_geo_low_poly_right_hand[];
extern const GeoLayout mario_vanish_geo_low_poly_body[];
extern const GeoLayout mario_metal_geo_face_and_wings[];
extern const GeoLayout mario_metal_geo_left_hand[];
extern const GeoLayout mario_metal_geo_right_hand[];
extern const GeoLayout mario_metal_geo_body[];
extern const GeoLayout mario_metal_geo_medium_poly_left_hand[];
extern const GeoLayout mario_metal_geo_medium_poly_right_hand[];
extern const GeoLayout mario_metal_geo_medium_poly_body[];
extern const GeoLayout mario_metal_geo_low_poly_face_and_wings[];
extern const GeoLayout mario_metal_geo_low_poly_left_hand[];
extern const GeoLayout mario_metal_geo_low_poly_right_hand[];
extern const GeoLayout mario_metal_geo_low_poly_body[];
extern const GeoLayout mario_metal_vanish_geo_face_and_wings[];
extern const GeoLayout mario_metal_vanish_geo_left_hand[];
extern const GeoLayout mario_metal_vanish_geo_right_hand[];
extern const GeoLayout mario_metal_vanish_geo_body[];
extern const GeoLayout mario_metal_vanish_geo_medium_poly_left_hand[];
extern const GeoLayout mario_metal_vanish_geo_medium_poly_right_hand[];
extern const GeoLayout mario_metal_vanish_geo_medium_poly_body[];
extern const GeoLayout mario_metal_vanish_geo_low_poly_face_and_wings[];
extern const GeoLayout mario_metal_vanish_geo_low_poly_left_hand[];
extern const GeoLayout mario_metal_vanish_geo_low_poly_right_hand[];
extern const GeoLayout mario_metal_vanish_geo_low_poly_body[];
extern const GeoLayout mario_geo_load_body[];
extern const GeoLayout mario_geo_load_medium_poly_body[];
extern const GeoLayout mario_geo_load_low_poly_body[];
extern const GeoLayout mario_geo_render_body[];
extern const GeoLayout mario_geo[];
extern const Gfx mario_butt_dl[];
extern const Gfx mario_butt[];
extern const Gfx mario_metal_butt[];
extern const Gfx mario_left_arm_shared_dl[];
extern const Gfx mario_left_arm[];
extern const Gfx mario_left_forearm_shared_dl[];
extern const Gfx mario_left_hand_closed_shared_dl[];
extern const Gfx mario_left_hand_closed[];
extern const Gfx mario_right_arm_shared_dl[];
extern const Gfx mario_right_arm[];
extern const Gfx mario_right_forearm_shared_dl[];
extern const Gfx mario_right_hand_closed_dl[];
extern const Gfx mario_right_hand_closed[];
extern const Gfx mario_metal_right_hand_closed[];
extern const Gfx mario_left_thigh_dl[];
extern const Gfx mario_left_thigh[];
extern const Gfx mario_metal_left_thigh[];
extern const Gfx mario_left_leg_shared_dl[];
extern const Gfx mario_left_foot_shared_dl[];
extern const Gfx mario_left_foot[];
extern const Gfx mario_right_thigh_shared_dl[];
extern const Gfx mario_right_thigh[];
extern const Gfx mario_right_leg_shared_dl[];
extern const Gfx mario_right_foot_dl[];
extern const Gfx mario_right_foot[];
extern const Gfx mario_metal_right_foot[];
extern const Gfx mario_yellow_button_dl[];
extern const Gfx mario_pants_overalls_shared_dl[];
extern const Gfx mario_tshirt_shared_dl[];
extern const Gfx mario_torso_dl[];
extern const Gfx mario_torso[];
extern const Gfx mario_metal_torso_shared_dl[];
extern const Gfx mario_m_logo_dl[];
extern const Gfx mario_eyes_cap_on_dl[];
extern const Gfx mario_hair_sideburn_cap_on_dl[];
extern const Gfx mario_mustache_cap_on_dl[];
extern const Gfx mario_face_part_cap_on_dl[];
extern const Gfx mario_face_cap_dl[];
extern const Gfx mario_face_back_hair_cap_on_dl[];
extern const Gfx mario_face_cap_on_dl[];
extern const Gfx mario_cap_on_eyes_front[];
extern const Gfx mario_cap_on_eyes_half_closed[];
extern const Gfx mario_cap_on_eyes_closed[];
extern const Gfx mario_cap_on_eyes_right[];
extern const Gfx mario_cap_on_eyes_left[];
extern const Gfx mario_cap_on_eyes_up[];
extern const Gfx mario_cap_on_eyes_down[];
extern const Gfx mario_cap_on_eyes_dead[];
extern const Gfx mario_metal_cap_on_shared_dl[];
extern const Gfx mario_eyes_cap_off_dl[];
extern const Gfx mario_mustache_cap_off_dl[];
extern const Gfx mario_hair_sideburn_cap_off_dl[];
extern const Gfx mario_face_part_cap_off_dl[];
extern const Gfx mario_face_hair_cap_off_dl[];
extern const Gfx mario_face_cap_off_dl[];
extern const Gfx mario_cap_off_eyes_front[];
extern const Gfx mario_cap_off_eyes_half_closed[];
extern const Gfx mario_cap_off_eyes_closed[];
extern const Gfx mario_cap_off_eyes_right[];
extern const Gfx mario_cap_off_eyes_left[];
extern const Gfx mario_cap_off_eyes_up[];
extern const Gfx mario_cap_off_eyes_down[];
extern const Gfx mario_cap_off_eyes_dead[];
extern const Gfx mario_metal_cap_off_shared_dl[];
extern const Gfx mario_medium_poly_butt_dl[];
extern const Gfx mario_medium_poly_butt[];
extern const Gfx mario_metal_medium_poly_butt[];
extern const Gfx mario_medium_poly_left_arm_shared_dl[];
extern const Gfx mario_medium_poly_left_arm[];
extern const Gfx mario_medium_poly_left_forearm_shared_dl[];
extern const Gfx mario_medium_poly_left_hand_closed_shared_dl[];
extern const Gfx mario_medium_poly_left_hand_closed[];
extern const Gfx mario_medium_poly_right_arm_shared_dl[];
extern const Gfx mario_medium_poly_right_arm[];
extern const Gfx mario_medium_poly_right_forearm_shared_dl[];
extern const Gfx mario_medium_poly_right_hand_closed_dl[];
extern const Gfx mario_medium_poly_right_hand_closed[];
extern const Gfx mario_metal_medium_poly_right_hand_closed[];
extern const Gfx mario_medium_poly_left_thigh_dl[];
extern const Gfx mario_medium_poly_left_thigh[];
extern const Gfx mario_metal_medium_poly_left_thigh[];
extern const Gfx mario_medium_poly_left_leg_shared_dl[];
extern const Gfx mario_medium_poly_left_foot_shared_dl[];
extern const Gfx mario_medium_poly_left_foot[];
extern const Gfx mario_medium_poly_right_thigh_shared_dl[];
extern const Gfx mario_medium_poly_right_thigh[];
extern const Gfx mario_medium_poly_right_leg_shared_dl[];
extern const Gfx mario_medium_poly_right_foot_dl[];
extern const Gfx mario_medium_poly_right_foot[];
extern const Gfx mario_metal_medium_poly_right_foot[];
extern const Gfx mario_medium_poly_yellow_button_dl[];
extern const Gfx mario_medium_poly_pants_overalls_shared_dl[];
extern const Gfx mario_medium_poly_tshirt_shared_dl[];
extern const Gfx mario_medium_poly_torso_dl[];
extern const Gfx mario_medium_poly_torso[];
extern const Gfx mario_metal_medium_poly_torso[];
extern const Gfx mario_low_poly_butt_dl[];
extern const Gfx mario_low_poly_butt[];
extern const Gfx mario_metal_low_poly_butt[];
extern const Gfx mario_low_poly_left_arm_shared_dl[];
extern const Gfx mario_low_poly_left_arm[];
extern const Gfx mario_low_poly_left_forearm_shared_dl[];
extern const Gfx mario_low_poly_left_hand_closed_shared_dl[];
extern const Gfx mario_low_poly_left_hand_closed[];
extern const Gfx mario_low_poly_right_arm_shared_dl[];
extern const Gfx mario_low_poly_right_arm[];
extern const Gfx mario_low_poly_right_forearm_shared_dl[];
extern const Gfx mario_low_poly_right_hand_closed_dl[];
extern const Gfx mario_low_poly_right_hand_closed[];
extern const Gfx mario_metal_low_poly_right_hand_closed[];
extern const Gfx mario_low_poly_left_thigh_dl[];
extern const Gfx mario_low_poly_left_thigh[];
extern const Gfx mario_metal_low_poly_left_thigh[];
extern const Gfx mario_low_poly_left_leg_shared_dl[];
extern const Gfx mario_low_poly_left_foot_shared_dl[];
extern const Gfx mario_low_poly_left_foot[];
extern const Gfx mario_low_poly_right_thigh_shared_dl[];
extern const Gfx mario_low_poly_right_thigh[];
extern const Gfx mario_low_poly_right_leg_shared_dl[];
extern const Gfx mario_low_poly_right_foot_dl[];
extern const Gfx mario_low_poly_right_foot[];
extern const Gfx mario_metal_low_poly_right_foot[];
extern const Gfx mario_low_poly_yellow_button_dl[];
extern const Gfx mario_low_poly_pants_overalls_shared_dl[];
extern const Gfx mario_low_poly_tshirt_shared_dl[];
extern const Gfx mario_low_poly_torso_dl[];
extern const Gfx mario_low_poly_torso[];
extern const Gfx mario_metal_low_poly_torso[];
extern const Gfx mario_low_poly_mario_m_logo_dl[];
extern const Gfx mario_low_poly_eyes_cap_on_dl[];
extern const Gfx mario_low_poly_mustache_cap_on_dl[];
extern const Gfx mario_low_poly_face_part_cap_on_dl[];
extern const Gfx mario_low_poly_face_cap_dl[];
extern const Gfx mario_low_poly_face_back_hair_cap_on_dl[];
extern const Gfx mario_low_poly_face_cap_on_dl[];
extern const Gfx mario_low_poly_cap_on_eyes_front[];
extern const Gfx mario_low_poly_cap_on_eyes_half_closed[];
extern const Gfx mario_low_poly_cap_on_eyes_closed[];
extern const Gfx mario_low_poly_cap_on_eyes_right[];
extern const Gfx mario_low_poly_cap_on_eyes_left[];
extern const Gfx mario_low_poly_cap_on_eyes_up[];
extern const Gfx mario_low_poly_cap_on_eyes_down[];
extern const Gfx mario_low_poly_cap_on_eyes_dead[];
extern const Gfx mario_metal_low_poly_cap_on[];
extern const Gfx mario_low_poly_mario_eyes_cap_off_dl[];
extern const Gfx mario_low_poly_mustache_cap_off_dl[];
extern const Gfx mario_low_poly_face_part_cap_off_dl[];
extern const Gfx mario_low_poly_face_hair_cap_off_dl[];
extern const Gfx mario_low_poly_face_cap_off_dl[];
extern const Gfx mario_low_poly_cap_off_eyes_front[];
extern const Gfx mario_low_poly_cap_off_eyes_half_closed[];
extern const Gfx mario_low_poly_cap_off_eyes_closed[];
extern const Gfx mario_low_poly_cap_off_eyes_right[];
extern const Gfx mario_low_poly_cap_off_eyes_left[];
extern const Gfx mario_low_poly_cap_off_eyes_up[];
extern const Gfx mario_low_poly_cap_off_eyes_down[];
extern const Gfx mario_low_poly_cap_off_eyes_dead[];
extern const Gfx mario_metal_low_poly_cap_off[];
extern const Gfx mario_left_hand_open_shared_dl[];
extern const Gfx mario_left_hand_open[];
extern const Gfx mario_right_hand_open_dl[];
extern const Gfx mario_right_hand_open[];
extern const Gfx mario_metal_right_hand_open[];
extern const Gfx mario_right_hand_cap_m_logo_dl[];
extern const Gfx mario_right_hand_cap_top_dl[];
extern const Gfx mario_right_hand_cap_hand_position_dl[];
extern const Gfx mario_right_hand_cap_bottom_dl[];
extern const Gfx mario_right_hand_cap_dl[];
extern const Gfx mario_right_hand_cap_wings_half_1_dl[];
extern const Gfx mario_right_hand_cap_wings_half_2_dl[];
extern const Gfx mario_right_hand_cap_wings_initial_dl[];
extern const Gfx mario_right_hand_cap_wings_end_dl[];
extern const Gfx mario_right_hand_cap[];
extern const Gfx mario_right_hand_cap_wings[];
extern const Gfx mario_metal_right_hand_cap_shared_dl[];
extern const Gfx mario_metal_right_hand_cap_shared_dl_wings[];
extern const Gfx mario_right_hand_peace_shared_dl[];
extern const Gfx mario_right_hand_peace[];
extern const Gfx mario_cap_unused_m_logo_dl[];
extern const Gfx mario_cap_unused_base_top_dl[];
extern const Gfx mario_cap_unused_base_bottom_dl[];
extern const Gfx mario_cap_unused_base_dl[];
extern const Gfx mario_wings_half_1_unused_dl[];
extern const Gfx mario_wings_half_2_unused_dl[];
extern const Gfx mario_cap_wings_unused_initial_dl[];
extern const Gfx mario_cap_wings_unused_end_dl[];
extern const Gfx mario_cap_unused_dl[];
extern const Gfx mario_metal_cap_unused_dl[];
extern const Gfx mario_cap_wings_unused[];
extern const Gfx mario_metal_cap_wings_unused[];
extern const Gfx mario_wings_half_1_dl[];
extern const Gfx mario_wings_half_2_dl[];
extern const Gfx mario_cap_wings[];
extern const Gfx mario_cap_wings_transparent[];
extern const Gfx mario_metal_cap_wings[];
extern const Gfx mario_metal_cap_wings_transparent[];

// luigi

extern const GeoLayout luigi_002_switch_opt0_001_switch_opt0_000_switch_opt1_000_switch_opt1[];
extern const GeoLayout luigi_002_switch_opt0_001_switch_opt0_000_switch_opt1_000_switch_opt2[];
extern const GeoLayout luigi_002_switch_opt0_001_switch_opt0_000_switch_opt1_000_switch_opt3[];
extern const GeoLayout luigi_002_switch_opt0_001_switch_opt0_000_switch_opt1_000_switch_opt4[];
extern const GeoLayout luigi_002_switch_opt0_001_switch_opt0_000_switch_opt1_000_switch_opt5[];
extern const GeoLayout luigi_002_switch_opt0_001_switch_opt0_000_switch_opt1_000_switch_opt6[];
extern const GeoLayout luigi_002_switch_opt0_001_switch_opt0_000_switch_opt1_000_switch_opt7[];
extern const GeoLayout luigi_luigi_cap_off[];
extern const GeoLayout luigi_luigi_left_hand_open[];
extern const GeoLayout luigi_luigi_right_hand_open[];
extern const GeoLayout luigi_luigi_right_hand_peace[];
extern const GeoLayout luigi_luigi_right_hand_cap[];
extern const GeoLayout luigi_luigi_right_hand_wing_cap[];
extern const GeoLayout luigi_002_switch_opt0_001_switch_opt1_000_switch_opt1_000_switch_opt1[];
extern const GeoLayout luigi_002_switch_opt0_001_switch_opt1_000_switch_opt1_000_switch_opt2[];
extern const GeoLayout luigi_002_switch_opt0_001_switch_opt1_000_switch_opt1_000_switch_opt3[];
extern const GeoLayout luigi_002_switch_opt0_001_switch_opt1_000_switch_opt1_000_switch_opt4[];
extern const GeoLayout luigi_002_switch_opt0_001_switch_opt1_000_switch_opt1_000_switch_opt5[];
extern const GeoLayout luigi_002_switch_opt0_001_switch_opt1_000_switch_opt1_000_switch_opt6[];
extern const GeoLayout luigi_002_switch_opt0_001_switch_opt1_000_switch_opt1_000_switch_opt7[];
extern const GeoLayout luigi_002_switch_opt0_001_switch_opt1_jump_luigi_luigi_cap_off[];
extern const GeoLayout luigi_002_switch_opt0_001_switch_opt1_jump_luigi_luigi_left_hand_open[];
extern const GeoLayout luigi_002_switch_opt0_001_switch_opt1_jump_luigi_luigi_right_hand_open[];
extern const GeoLayout luigi_002_switch_opt0_001_switch_opt1_jump_luigi_luigi_right_hand_peace[];
extern const GeoLayout luigi_002_switch_opt0_001_switch_opt1_jump_luigi_luigi_right_hand_cap[];
extern const GeoLayout luigi_002_switch_opt0_001_switch_opt1_jump_luigi_luigi_right_hand_wing_cap[];
extern const GeoLayout luigi_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt1[];
extern const GeoLayout luigi_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt2[];
extern const GeoLayout luigi_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt3[];
extern const GeoLayout luigi_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt4[];
extern const GeoLayout luigi_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt5[];
extern const GeoLayout luigi_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt6[];
extern const GeoLayout luigi_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt7[];
extern const GeoLayout luigi_002_switch_opt0_001_switch_opt1[];
extern const GeoLayout luigi_002_switch_opt0_001_switch_opt2_jump_luigi_luigi_cap_off[];
extern const GeoLayout luigi_002_switch_opt0_001_switch_opt2_jump_luigi_luigi_left_hand_open[];
extern const GeoLayout luigi_002_switch_opt0_001_switch_opt2_jump_luigi_luigi_right_hand_open[];
extern const GeoLayout luigi_002_switch_opt0_001_switch_opt2_jump_luigi_luigi_right_hand_peace[];
extern const GeoLayout luigi_002_switch_opt0_001_switch_opt2_jump_luigi_luigi_right_hand_cap[];
extern const GeoLayout luigi_002_switch_opt0_001_switch_opt2_jump_luigi_luigi_right_hand_wing_cap[];
extern const GeoLayout luigi_002_switch_opt0_001_switch_opt2[];
extern const GeoLayout luigi_002_switch_opt0_001_switch_opt3_jump_luigi_luigi_cap_off[];
extern const GeoLayout luigi_002_switch_opt0_001_switch_opt3_jump_luigi_luigi_left_hand_open[];
extern const GeoLayout luigi_002_switch_opt0_001_switch_opt3_jump_luigi_luigi_right_hand_open[];
extern const GeoLayout luigi_002_switch_opt0_001_switch_opt3_jump_luigi_luigi_right_hand_peace[];
extern const GeoLayout luigi_002_switch_opt0_001_switch_opt3_jump_luigi_luigi_right_hand_cap[];
extern const GeoLayout luigi_002_switch_opt0_001_switch_opt3_jump_luigi_luigi_right_hand_wing_cap[];
extern const GeoLayout luigi_002_switch_opt0_001_switch_opt3[];
extern const GeoLayout luigi_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt1[];
extern const GeoLayout luigi_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt2[];
extern const GeoLayout luigi_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt3[];
extern const GeoLayout luigi_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt4[];
extern const GeoLayout luigi_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt5[];
extern const GeoLayout luigi_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt6[];
extern const GeoLayout luigi_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt7[];
extern const GeoLayout luigi_geo[];
extern Lights1 luigi_luigi_blue_lights;
extern Lights1 luigi_luigi_overalls_button_lights;
extern Lights1 luigi_luigi_green_lights;
extern Lights1 luigi_luigi_logo_lights;
extern Lights1 luigi_luigi_sideburn_lights;
extern Lights1 luigi_eyes_center_lights;
extern Lights1 luigi_luigi_beige_lights;
extern Lights1 luigi_luigi_mustache_lights;
extern Lights1 luigi_luigi_brown2_lights;
extern Lights1 luigi_eyes_half_closed_lights;
extern Lights1 luigi_eyes_closed_lights;
extern Lights1 luigi_eyes_right_lights;
extern Lights1 luigi_eyes_left_lights;
extern Lights1 luigi_eyes_up_lights;
extern Lights1 luigi_eyes_down_lights;
extern Lights1 luigi_eyes_dead_lights;
extern Lights1 luigi_luigi_white_lights;
extern Lights1 luigi_luigi_cap_inside_green_lights;
extern Lights1 luigi_mario_right_hand_cap_wing_lights;
extern Lights1 luigi_mario_right_hand_cap_wing_tip_lights;
extern Lights1 luigi_luigi_brown1_lights;
extern u8 luigi_mario_metal_rgba16[];
extern u8 luigi_mario_overalls_button_rgba16[];
extern u8 luigi_custom_luigi_logo_rgba16[];
extern u8 luigi_custom_luigi_sideburn_rgba16[];
extern u8 luigi_mario_eyes_center_rgba16[];
extern u8 luigi_custom_luigi_mustache_rgba16[];
extern u8 luigi_mario_eyes_half_closed_rgba16[];
extern u8 luigi_mario_eyes_closed_rgba16[];
extern u8 luigi_Happy_rgba16[];
extern u8 luigi_mario_eyes_right_unused_rgba16[];
extern u8 luigi_mario_eyes_up_unused_rgba16[];
extern u8 luigi_mario_eyes_down_unused_rgba16[];
extern u8 luigi_mario_eyes_dead_rgba16[];
extern u8 luigi_mario_wing_rgba16[];
extern u8 luigi_mario_wing_tip_rgba16[];
extern Vtx luigi_000_offset_butt_mesh_layer_1_vtx_0[76];
extern Gfx luigi_000_offset_butt_mesh_layer_1_tri_0[];
extern Vtx luigi_000_offset_torso_mesh_layer_1_vtx_0[14];
extern Gfx luigi_000_offset_torso_mesh_layer_1_tri_0[];
extern Vtx luigi_000_offset_torso_mesh_layer_1_vtx_1[94];
extern Gfx luigi_000_offset_torso_mesh_layer_1_tri_1[];
extern Vtx luigi_000_offset_torso_mesh_layer_1_vtx_2[30];
extern Gfx luigi_000_offset_torso_mesh_layer_1_tri_2[];
extern Vtx luigi_000_displaylist_cap_on_mesh_layer_1_vtx_0[55];
extern Gfx luigi_000_displaylist_cap_on_mesh_layer_1_tri_0[];
extern Vtx luigi_000_displaylist_cap_on_mesh_layer_1_vtx_1[12];
extern Gfx luigi_000_displaylist_cap_on_mesh_layer_1_tri_1[];
extern Vtx luigi_000_displaylist_cap_on_mesh_layer_1_vtx_2[12];
extern Gfx luigi_000_displaylist_cap_on_mesh_layer_1_tri_2[];
extern Vtx luigi_000_displaylist_cap_on_mesh_layer_1_vtx_3[90];
extern Gfx luigi_000_displaylist_cap_on_mesh_layer_1_tri_3[];
extern Vtx luigi_000_displaylist_cap_on_mesh_layer_1_vtx_4[21];
extern Gfx luigi_000_displaylist_cap_on_mesh_layer_1_tri_4[];
extern Vtx luigi_000_displaylist_cap_on_mesh_layer_1_vtx_5[24];
extern Gfx luigi_000_displaylist_cap_on_mesh_layer_1_tri_5[];
extern Vtx luigi_000_switch_option_000_displaylist_cap_off_mesh_layer_1_vtx_0[12];
extern Gfx luigi_000_switch_option_000_displaylist_cap_off_mesh_layer_1_tri_0[];
extern Vtx luigi_000_switch_option_000_displaylist_cap_off_mesh_layer_1_vtx_1[90];
extern Gfx luigi_000_switch_option_000_displaylist_cap_off_mesh_layer_1_tri_1[];
extern Vtx luigi_000_switch_option_000_displaylist_cap_off_mesh_layer_1_vtx_2[100];
extern Gfx luigi_000_switch_option_000_displaylist_cap_off_mesh_layer_1_tri_2[];
extern Vtx luigi_000_switch_option_000_displaylist_cap_off_mesh_layer_1_vtx_3[12];
extern Gfx luigi_000_switch_option_000_displaylist_cap_off_mesh_layer_1_tri_3[];
extern Vtx luigi_000_switch_option_000_displaylist_cap_off_mesh_layer_1_vtx_4[21];
extern Gfx luigi_000_switch_option_000_displaylist_cap_off_mesh_layer_1_tri_4[];
extern Vtx luigi_000_displaylist_right_wing_mesh_layer_4_vtx_0[4];
extern Gfx luigi_000_displaylist_right_wing_mesh_layer_4_tri_0[];
extern Vtx luigi_000_displaylist_right_wing_mesh_layer_4_vtx_1[4];
extern Gfx luigi_000_displaylist_right_wing_mesh_layer_4_tri_1[];
extern Vtx luigi_000_displaylist_left_wing_mesh_layer_4_vtx_0[4];
extern Gfx luigi_000_displaylist_left_wing_mesh_layer_4_tri_0[];
extern Vtx luigi_000_displaylist_left_wing_mesh_layer_4_vtx_1[4];
extern Gfx luigi_000_displaylist_left_wing_mesh_layer_4_tri_1[];
extern Vtx luigi_000_offset_left_upperarm_mesh_layer_1_vtx_0[29];
extern Gfx luigi_000_offset_left_upperarm_mesh_layer_1_tri_0[];
extern Vtx luigi_000_offset_left_forearm_mesh_layer_1_vtx_0[16];
extern Gfx luigi_000_offset_left_forearm_mesh_layer_1_tri_0[];
extern Vtx luigi_000_displaylist_left_hand_closed_mesh_layer_1_vtx_0[44];
extern Gfx luigi_000_displaylist_left_hand_closed_mesh_layer_1_tri_0[];
extern Vtx luigi_000_switch_option_000_offset_left_hand_open_mesh_layer_1_vtx_0[63];
extern Gfx luigi_000_switch_option_000_offset_left_hand_open_mesh_layer_1_tri_0[];
extern Vtx luigi_000_offset_right_upperarm_mesh_layer_1_vtx_0[30];
extern Gfx luigi_000_offset_right_upperarm_mesh_layer_1_tri_0[];
extern Vtx luigi_000_offset_right_forearm_mesh_layer_1_vtx_0[16];
extern Gfx luigi_000_offset_right_forearm_mesh_layer_1_tri_0[];
extern Vtx luigi_000_displaylist_right_hand_closed_mesh_layer_1_vtx_0[41];
extern Gfx luigi_000_displaylist_right_hand_closed_mesh_layer_1_tri_0[];
extern Vtx luigi_001_switch_option_000_offset_right_hand_open_mesh_layer_1_vtx_0[61];
extern Gfx luigi_001_switch_option_000_offset_right_hand_open_mesh_layer_1_tri_0[];
extern Vtx luigi_001_switch_option_000_offset_right_hand_peace_mesh_layer_1_vtx_0[113];
extern Gfx luigi_001_switch_option_000_offset_right_hand_peace_mesh_layer_1_tri_0[];
extern Vtx luigi_001_switch_option_000_offset_right_hand_cap_mesh_layer_1_vtx_0[5];
extern Gfx luigi_001_switch_option_000_offset_right_hand_cap_mesh_layer_1_tri_0[];
extern Vtx luigi_001_switch_option_000_offset_right_hand_cap_mesh_layer_1_vtx_1[51];
extern Gfx luigi_001_switch_option_000_offset_right_hand_cap_mesh_layer_1_tri_1[];
extern Vtx luigi_001_switch_option_000_offset_right_hand_cap_mesh_layer_1_vtx_2[10];
extern Gfx luigi_001_switch_option_000_offset_right_hand_cap_mesh_layer_1_tri_2[];
extern Vtx luigi_001_switch_option_000_offset_right_hand_cap_mesh_layer_1_vtx_3[46];
extern Gfx luigi_001_switch_option_000_offset_right_hand_cap_mesh_layer_1_tri_3[];
extern Vtx luigi_001_switch_option_000_offset_right_hand_wing_cap_mesh_layer_1_vtx_0[5];
extern Gfx luigi_001_switch_option_000_offset_right_hand_wing_cap_mesh_layer_1_tri_0[];
extern Vtx luigi_001_switch_option_000_offset_right_hand_wing_cap_mesh_layer_1_vtx_1[51];
extern Gfx luigi_001_switch_option_000_offset_right_hand_wing_cap_mesh_layer_1_tri_1[];
extern Vtx luigi_001_switch_option_000_offset_right_hand_wing_cap_mesh_layer_1_vtx_2[10];
extern Gfx luigi_001_switch_option_000_offset_right_hand_wing_cap_mesh_layer_1_tri_2[];
extern Vtx luigi_001_switch_option_000_offset_right_hand_wing_cap_mesh_layer_1_vtx_3[46];
extern Gfx luigi_001_switch_option_000_offset_right_hand_wing_cap_mesh_layer_1_tri_3[];
extern Vtx luigi_001_switch_option_000_displaylist_right_hand_cap_wings_mesh_layer_4_vtx_0[10];
extern Gfx luigi_001_switch_option_000_displaylist_right_hand_cap_wings_mesh_layer_4_tri_0[];
extern Vtx luigi_001_switch_option_000_displaylist_right_hand_cap_wings_mesh_layer_4_vtx_1[8];
extern Gfx luigi_001_switch_option_000_displaylist_right_hand_cap_wings_mesh_layer_4_tri_1[];
extern Vtx luigi_000_offset_left_thigh_mesh_layer_1_vtx_0[22];
extern Gfx luigi_000_offset_left_thigh_mesh_layer_1_tri_0[];
extern Vtx luigi_000_offset_left_leg_mesh_layer_1_vtx_0[12];
extern Gfx luigi_000_offset_left_leg_mesh_layer_1_tri_0[];
extern Vtx luigi_000_offset_left_foot_mesh_layer_1_vtx_0[28];
extern Gfx luigi_000_offset_left_foot_mesh_layer_1_tri_0[];
extern Vtx luigi_000_offset_right_thigh_mesh_layer_1_vtx_0[26];
extern Gfx luigi_000_offset_right_thigh_mesh_layer_1_tri_0[];
extern Vtx luigi_000_offset_right_leg_mesh_layer_1_vtx_0[22];
extern Gfx luigi_000_offset_right_leg_mesh_layer_1_tri_0[];
extern Vtx luigi_000_displaylist_right_foot_mesh_layer_1_vtx_0[28];
extern Gfx luigi_000_displaylist_right_foot_mesh_layer_1_tri_0[];
extern Gfx mat_luigi_luigi_blue[];
extern Gfx mat_luigi_metal[];
extern Gfx mat_revert_luigi_metal[];
extern Gfx mat_luigi_luigi_overalls_button[];
extern Gfx mat_luigi_luigi_green[];
extern Gfx mat_luigi_luigi_logo[];
extern Gfx mat_luigi_luigi_sideburn[];
extern Gfx mat_luigi_eyes_center[];
extern Gfx mat_luigi_luigi_beige[];
extern Gfx mat_luigi_luigi_mustache[];
extern Gfx mat_luigi_luigi_brown2[];
extern Gfx mat_luigi_eyes_half_closed[];
extern Gfx mat_luigi_eyes_closed[];
extern Gfx mat_luigi_eyes_right[];
extern Gfx mat_luigi_eyes_left[];
extern Gfx mat_luigi_eyes_up[];
extern Gfx mat_luigi_eyes_down[];
extern Gfx mat_luigi_eyes_dead[];
extern Gfx mat_luigi_mario_wing[];
extern Gfx mat_revert_luigi_mario_wing[];
extern Gfx mat_luigi_mario_wing_tip[];
extern Gfx mat_revert_luigi_mario_wing_tip[];
extern Gfx mat_luigi_luigi_white[];
extern Gfx mat_luigi_luigi_cap_inside_green[];
extern Gfx mat_luigi_mario_right_hand_cap_wing[];
extern Gfx mat_revert_luigi_mario_right_hand_cap_wing[];
extern Gfx mat_luigi_mario_right_hand_cap_wing_tip[];
extern Gfx mat_revert_luigi_mario_right_hand_cap_wing_tip[];
extern Gfx mat_luigi_luigi_brown1[];
extern Gfx luigi_000_offset_butt_mesh_layer_1[];
extern Gfx luigi_000_offset_butt_mesh_layer_1_mat_override_metal_0[];
extern Gfx luigi_000_offset_torso_mesh_layer_1[];
extern Gfx luigi_000_offset_torso_mesh_layer_1_mat_override_metal_0[];
extern Gfx luigi_000_displaylist_cap_on_mesh_layer_1[];
extern Gfx luigi_000_displaylist_cap_on_mesh_layer_1_mat_override_metal_0[];
extern Gfx luigi_000_displaylist_cap_on_mesh_layer_1_mat_override_eyes_half_closed_1[];
extern Gfx luigi_000_displaylist_cap_on_mesh_layer_1_mat_override_eyes_closed_2[];
extern Gfx luigi_000_displaylist_cap_on_mesh_layer_1_mat_override_eyes_right_3[];
extern Gfx luigi_000_displaylist_cap_on_mesh_layer_1_mat_override_eyes_left_4[];
extern Gfx luigi_000_displaylist_cap_on_mesh_layer_1_mat_override_eyes_up_5[];
extern Gfx luigi_000_displaylist_cap_on_mesh_layer_1_mat_override_eyes_down_6[];
extern Gfx luigi_000_displaylist_cap_on_mesh_layer_1_mat_override_eyes_dead_7[];
extern Gfx luigi_000_switch_option_000_displaylist_cap_off_mesh_layer_1[];
extern Gfx luigi_000_switch_option_000_displaylist_cap_off_mesh_layer_1_mat_override_metal_0[];
extern Gfx luigi_000_switch_option_000_displaylist_cap_off_mesh_layer_1_mat_override_eyes_half_closed_1[];
extern Gfx luigi_000_switch_option_000_displaylist_cap_off_mesh_layer_1_mat_override_eyes_closed_2[];
extern Gfx luigi_000_switch_option_000_displaylist_cap_off_mesh_layer_1_mat_override_eyes_right_3[];
extern Gfx luigi_000_switch_option_000_displaylist_cap_off_mesh_layer_1_mat_override_eyes_left_4[];
extern Gfx luigi_000_switch_option_000_displaylist_cap_off_mesh_layer_1_mat_override_eyes_up_5[];
extern Gfx luigi_000_switch_option_000_displaylist_cap_off_mesh_layer_1_mat_override_eyes_down_6[];
extern Gfx luigi_000_switch_option_000_displaylist_cap_off_mesh_layer_1_mat_override_eyes_dead_7[];
extern Gfx luigi_000_displaylist_right_wing_mesh_layer_4[];
extern Gfx luigi_000_displaylist_right_wing_mesh_layer_4_mat_override_metal_0[];
extern Gfx luigi_000_displaylist_left_wing_mesh_layer_4[];
extern Gfx luigi_000_displaylist_left_wing_mesh_layer_4_mat_override_metal_0[];
extern Gfx luigi_000_offset_left_upperarm_mesh_layer_1[];
extern Gfx luigi_000_offset_left_upperarm_mesh_layer_1_mat_override_metal_0[];
extern Gfx luigi_000_offset_left_forearm_mesh_layer_1[];
extern Gfx luigi_000_offset_left_forearm_mesh_layer_1_mat_override_metal_0[];
extern Gfx luigi_000_displaylist_left_hand_closed_mesh_layer_1[];
extern Gfx luigi_000_displaylist_left_hand_closed_mesh_layer_1_mat_override_metal_0[];
extern Gfx luigi_000_switch_option_000_offset_left_hand_open_mesh_layer_1[];
extern Gfx luigi_000_switch_option_000_offset_left_hand_open_mesh_layer_1_mat_override_metal_0[];
extern Gfx luigi_000_offset_right_upperarm_mesh_layer_1[];
extern Gfx luigi_000_offset_right_upperarm_mesh_layer_1_mat_override_metal_0[];
extern Gfx luigi_000_offset_right_forearm_mesh_layer_1[];
extern Gfx luigi_000_offset_right_forearm_mesh_layer_1_mat_override_metal_0[];
extern Gfx luigi_000_displaylist_right_hand_closed_mesh_layer_1[];
extern Gfx luigi_000_displaylist_right_hand_closed_mesh_layer_1_mat_override_metal_0[];
extern Gfx luigi_001_switch_option_000_offset_right_hand_open_mesh_layer_1[];
extern Gfx luigi_001_switch_option_000_offset_right_hand_open_mesh_layer_1_mat_override_metal_0[];
extern Gfx luigi_001_switch_option_000_offset_right_hand_peace_mesh_layer_1[];
extern Gfx luigi_001_switch_option_000_offset_right_hand_peace_mesh_layer_1_mat_override_metal_0[];
extern Gfx luigi_001_switch_option_000_offset_right_hand_cap_mesh_layer_1[];
extern Gfx luigi_001_switch_option_000_offset_right_hand_cap_mesh_layer_1_mat_override_metal_0[];
extern Gfx luigi_001_switch_option_000_offset_right_hand_wing_cap_mesh_layer_1[];
extern Gfx luigi_001_switch_option_000_offset_right_hand_wing_cap_mesh_layer_1_mat_override_metal_0[];
extern Gfx luigi_001_switch_option_000_displaylist_right_hand_cap_wings_mesh_layer_4[];
extern Gfx luigi_001_switch_option_000_displaylist_right_hand_cap_wings_mesh_layer_4_mat_override_metal_0[];
extern Gfx luigi_000_offset_left_thigh_mesh_layer_1[];
extern Gfx luigi_000_offset_left_thigh_mesh_layer_1_mat_override_metal_0[];
extern Gfx luigi_000_offset_left_leg_mesh_layer_1[];
extern Gfx luigi_000_offset_left_leg_mesh_layer_1_mat_override_metal_0[];
extern Gfx luigi_000_offset_left_foot_mesh_layer_1[];
extern Gfx luigi_000_offset_left_foot_mesh_layer_1_mat_override_metal_0[];
extern Gfx luigi_000_offset_right_thigh_mesh_layer_1[];
extern Gfx luigi_000_offset_right_thigh_mesh_layer_1_mat_override_metal_0[];
extern Gfx luigi_000_offset_right_leg_mesh_layer_1[];
extern Gfx luigi_000_offset_right_leg_mesh_layer_1_mat_override_metal_0[];
extern Gfx luigi_000_displaylist_right_foot_mesh_layer_1[];
extern Gfx luigi_000_displaylist_right_foot_mesh_layer_1_mat_override_metal_0[];
extern Gfx luigi_material_revert_render_settings[];


// sparkle
extern const GeoLayout sparkles_geo[];
extern const Gfx sparkles_seg4_dl_0402A490[];
extern const Gfx sparkles_seg4_dl_0402A4F8[];
extern const Gfx sparkles_seg4_dl_0402A510[];
extern const Gfx sparkles_seg4_dl_0402A528[];
extern const Gfx sparkles_seg4_dl_0402A540[];
extern const Gfx sparkles_seg4_dl_0402A558[];
extern const Gfx sparkles_seg4_dl_0402A570[];

// sparkle_animation
extern const GeoLayout sparkles_animation_geo[];
extern const Gfx sparkles_animation_seg4_dl_04035288[];
extern const Gfx sparkles_animation_seg4_dl_04035300[];
extern const Gfx sparkles_animation_seg4_dl_04035318[];
extern const Gfx sparkles_animation_seg4_dl_04035330[];
extern const Gfx sparkles_animation_seg4_dl_04035348[];
extern const Gfx sparkles_animation_seg4_dl_04035360[];

// small water splash
extern const GeoLayout small_water_splash_geo[];
extern const Gfx small_water_splash_seg4_dl_0[];
extern const Gfx small_water_splash_seg4_dl_1[];
extern const Gfx small_water_splash_seg4_dl_2[];
extern const Gfx small_water_splash_seg4_dl_3[];
extern const Gfx small_water_splash_seg4_dl_4[];
extern const Gfx small_water_splash_seg4_dl_5[];

// walk_smoke
extern const GeoLayout smoke_geo[];
extern const Gfx smoke_seg4_dl_040216A0[];
extern const Gfx smoke_seg4_dl_04021718[];
extern const Gfx smoke_seg4_dl_04021730[];
extern const Gfx smoke_seg4_dl_04021748[];
extern const Gfx smoke_seg4_dl_04021760[];
extern const Gfx smoke_seg4_dl_04021778[];
extern const Gfx smoke_seg4_dl_04021790[];
extern const Gfx smoke_seg4_dl_040217A8[];

// water_splash
extern const GeoLayout water_splash_geo[];
extern const Gfx water_splash_seg4_dl_040325C8[];
extern const Gfx water_splash_seg4_dl_04032640[];
extern const Gfx water_splash_seg4_dl_04032658[];
extern const Gfx water_splash_seg4_dl_04032670[];
extern const Gfx water_splash_seg4_dl_04032688[];
extern const Gfx water_splash_seg4_dl_040326A0[];
extern const Gfx water_splash_seg4_dl_040326B8[];
extern const Gfx water_splash_seg4_dl_040326D0[];
extern const Gfx water_splash_seg4_dl_040326E8[];

// water_waves
extern const GeoLayout idle_water_wave_geo[];
extern const GeoLayout wave_trail_geo[];
extern const Gfx water_wave_seg4_dl_04027358[];
extern const Gfx water_wave_seg4_dl_040273A0[];
extern const Gfx water_wave_seg4_dl_040273D8[];
extern const Gfx water_wave_seg4_dl_040273F0[];
extern const Gfx water_wave_seg4_dl_04027408[];
extern const Gfx water_wave_seg4_dl_04027420[];
extern const Gfx water_wave_seg4_dl_04027438[];

// white_particle_small
extern const Gfx white_particle_small_dl_begin[];
extern const Gfx white_particle_small_dl_end[];
extern const Gfx white_particle_small_dl[];
extern const Gfx white_particle_small_unused_dl[];

#include "wario/geo_header.h"

#include "waluigi/geo_header.h"

#include "luigi/geo_header.h"

#include "mario/collision_header.h"

#include "apparition/geo_header.h"


#include "luigi/anim_header.h"
#include "mario/geo_header.h"

#endif
