#include <ultra64.h>
#include "sm64.h"
#include "surface_terrains.h"
#include "moving_texture_macros.h"
#include "surface_terrains.h"
#include "textures.h"
#include "dialog_ids.h"

#include "make_const_nonconst.h"

#include "actors_vanilla/wf/header.h"

#include "actors_vanilla/wf/texture.inc.c"

#include "actors_vanilla/wf/small_bomp/1.inc.c"
#include "actors_vanilla/wf/small_bomp/2.inc.c"
#include "actors_vanilla/wf/large_bomp/model.inc.c"
#include "actors_vanilla/wf/tumbling_bridge_near/model.inc.c"
#include "actors_vanilla/wf/tumbling_bridge_far/model.inc.c"
#include "actors_vanilla/wf/rotating_wooden_platform/1.inc.c"
#include "actors_vanilla/wf/rotating_wooden_platform/2.inc.c"
#include "actors_vanilla/wf/sliding_platform/model.inc.c"
#include "actors_vanilla/wf/beta_extending_platform/model.inc.c"
#include "actors_vanilla/wf/extending_platform/model.inc.c"
#include "actors_vanilla/wf/breakable_wall_right/model.inc.c"
#include "actors_vanilla/wf/breakable_wall_left/model.inc.c"
#include "actors_vanilla/wf/giant_pole/model.inc.c"
#include "actors_vanilla/wf/rotating_platform/model.inc.c"
#include "actors_vanilla/wf/10/1.inc.c"
#include "actors_vanilla/wf/10/2.inc.c"
#include "actors_vanilla/wf/11/model.inc.c"

#include "actors_vanilla/wf/kickable_board/1.inc.c"
#include "actors_vanilla/wf/kickable_board/2.inc.c"
#include "actors_vanilla/wf/tower_door/model.inc.c"
#include "actors_vanilla/wf/small_bomp/collision.inc.c"
#include "actors_vanilla/wf/large_bomp/collision.inc.c"
#include "actors_vanilla/wf/rotating_wooden_platform/collision.inc.c"
#include "actors_vanilla/wf/sliding_platform/collision.inc.c"
#include "actors_vanilla/wf/tumbling_bridge_near/collision.inc.c"
#include "actors_vanilla/wf/beta_extending_platform/collision.inc.c"
#include "actors_vanilla/wf/extending_platform/collision.inc.c"
#include "actors_vanilla/wf/breakable_wall_right/collision.inc.c"
#include "actors_vanilla/wf/breakable_wall_left/collision.inc.c"
#include "actors_vanilla/wf/kickable_board/collision.inc.c"
#include "actors_vanilla/wf/tower_door/collision.inc.c"
#include "actors_vanilla/wf/rotating_platform/collision.inc.c"
#include "actors_vanilla/wf/10/collision.inc.c"
#include "actors_vanilla/wf/11/collision.inc.c"
