extern const GeoLayout lighting_engine_demo_area_1_geo[];
extern const GeoLayout lighting_engine_demo_area_1[];
extern const Collision lighting_engine_demo_area_1_collision[];
extern const MacroObject lighting_engine_demo_area_1_macro_objs[];

extern u8 lighting_engine_demo_dl_stripes_i4[];
extern u8 lighting_engine_demo_dl_checkerboard_ci4[];
extern u8 lighting_engine_demo_dl_checkerboard_pal_rgba16[];
extern Vtx lighting_engine_demo_dl_Column_mesh_layer_1_vtx_cull[8];
extern Vtx lighting_engine_demo_dl_Column_mesh_layer_1_vtx_0[59];
extern Gfx lighting_engine_demo_dl_Column_mesh_layer_1_tri_0[];
extern Vtx lighting_engine_demo_dl_Icosphere_mesh_layer_1_vtx_cull[8];
extern Vtx lighting_engine_demo_dl_Icosphere_mesh_layer_1_vtx_0[90];
extern Gfx lighting_engine_demo_dl_Icosphere_mesh_layer_1_tri_0[];
extern Vtx lighting_engine_demo_dl_Plane_mesh_layer_1_vtx_cull[8];
extern Vtx lighting_engine_demo_dl_Plane_mesh_layer_1_vtx_0[99];
extern Gfx lighting_engine_demo_dl_Plane_mesh_layer_1_tri_0[];
extern Gfx mat_lighting_engine_demo_dl_column_v3[];
extern Gfx mat_revert_lighting_engine_demo_dl_column_v3[];
extern Gfx mat_lighting_engine_demo_dl_f3dlite_material[];
extern Gfx mat_lighting_engine_demo_dl_checkerboard_v3[];
extern Gfx mat_revert_lighting_engine_demo_dl_checkerboard_v3[];
extern Gfx lighting_engine_demo_dl_Column_mesh_layer_1[];
extern Gfx lighting_engine_demo_dl_Icosphere_mesh_layer_1[];
extern Gfx lighting_engine_demo_dl_Plane_mesh_layer_1[];
extern Gfx lighting_engine_demo_dl_material_revert_render_settings[];
