#include "levels/bob/texture.inc.c"
#include "levels/bob/areas/1/1/model.inc.c"
#include "levels/bob/areas/1/2/model.inc.c"
#include "levels/bob/areas/1/3/model.inc.c"
#include "levels/bob/areas/1/4/model.inc.c"
#include "levels/bob/areas/1/5/model.inc.c"
#include "levels/bob/areas/1/6/model.inc.c"
#include "levels/bob/areas/1/collision.inc.c"
