#pragma once

#include "types.h"
#include "game/camera.h"

void cam_bbh_room_6(struct Camera *c);
void cam_bbh_fall_off_roof(struct Camera *c);
void cam_bbh_fall_into_pool(struct Camera *c);
void cam_bbh_room_1(struct Camera *c);
void cam_bbh_leave_front_door(struct Camera *c);
void cam_bbh_room_2_lower(struct Camera *c);
void cam_bbh_room_4(struct Camera *c);
void cam_bbh_room_8(struct Camera *c);
void cam_bbh_room_5_library(struct Camera *c);
void cam_bbh_room_5_library_to_hidden_transition(struct Camera *c);
void cam_bbh_room_5_hidden_to_library_transition(struct Camera *c);
void cam_bbh_room_5_hidden(struct Camera *c);
void cam_bbh_room_3(struct Camera *c);
void cam_bbh_room_7_mr_i(struct Camera *c);
void cam_bbh_room_7_mr_i_to_coffins_transition(struct Camera *c);
void cam_bbh_room_7_coffins_to_mr_i_transition(struct Camera *c);
void cam_bbh_elevator_room_lower(struct Camera *c);
void cam_bbh_room_0_back_entrance(struct Camera *c);
void cam_bbh_elevator(struct Camera *c);
void cam_bbh_room_12_upper(struct Camera *c);
void cam_bbh_enter_front_door(struct Camera *c);
void cam_bbh_room_2_library(struct Camera *c);
void cam_bbh_room_2_library_to_trapdoor_transition(struct Camera *c);
void cam_bbh_room_2_trapdoor(struct Camera *c);
void cam_bbh_room_2_trapdoor_transition(struct Camera *c);
void cam_bbh_room_9_attic(struct Camera *c);
void cam_bbh_room_9_attic_transition(struct Camera *c);
void cam_bbh_room_9_mr_i_transition(struct Camera *c);
void cam_bbh_room_13_balcony(struct Camera *c);
void cam_bbh_room_0(struct Camera *c);
void cam_bob_tower(struct Camera *c);
void cam_bob_default_free_roam(struct Camera *c);
void cam_bob_tower(struct Camera *c);
void cam_bob_default_free_roam(struct Camera *c);
void cam_castle_hmc_start_pool_cutscene(struct Camera *c);
void cam_castle_lobby_entrance(UNUSED struct Camera *c);
void cam_castle_look_upstairs(struct Camera *c);
void cam_castle_basement_look_downstairs(struct Camera *c);
void cam_castle_enter_lobby(struct Camera *c);
void cam_castle_enter_spiral_stairs(struct Camera *c);
void cam_castle_leave_spiral_stairs(struct Camera *c);
void cam_castle_close_mode(struct Camera *c);
void cam_castle_leave_lobby_sliding_door(struct Camera *c);
void cam_castle_enter_lobby_sliding_door(struct Camera *c);
void cam_ccm_enter_slide_shortcut(UNUSED struct Camera *c);
void cam_ccm_leave_slide_shortcut(UNUSED struct Camera *c);
void cam_cotmc_exit_waterfall(UNUSED struct Camera *c);
void move_camera_through_floor_while_descending(struct Camera *c, f32 height);
void cam_hmc_enter_maze(struct Camera *c);
void cam_hmc_elevator_black_hole(struct Camera *c);
void cam_hmc_elevator_maze_emergency_exit(struct Camera *c);
void cam_hmc_elevator_lake(struct Camera *c);
void cam_hmc_elevator_maze(struct Camera *c);
void cam_rr_exit_building_side(struct Camera *c);
void cam_rr_exit_building_top(struct Camera *c);
void cam_rr_enter_building_window(struct Camera *c);
void cam_rr_enter_building(struct Camera *c);
void cam_rr_enter_building_side(struct Camera *c);
void cam_sl_snowman_head_8dir(struct Camera *c);
void cam_sl_free_roam(struct Camera *c);
void cam_ssl_enter_pyramid_top(UNUSED struct Camera *c);
void cam_ssl_pyramid_center(struct Camera *c);
void cam_ssl_boss_room(struct Camera *c);
void cam_thi_move_cam_through_tunnel(UNUSED struct Camera *c);
void cam_thi_look_through_tunnel(UNUSED struct Camera *c);