#include "levels/cotmc/texture.inc.c"
#include "levels/cotmc/areas/1/1/model.inc.c"
#include "levels/cotmc/areas/1/2/model.inc.c"
#include "levels/cotmc/areas/1/3/model.inc.c"
#include "levels/cotmc/areas/1/collision.inc.c"
