#include <PR/ultratypes.h>
#include <PR/gbi.h>

#include "dialog_ids.h"
#include "surface_terrains.h"
#include "macros.h"
#include "moving_texture_macros.h"
#include "surface_terrains.h"
#include "textures.h"
#include "types.h"

#include "make_const_nonconst.h"

#include "actors/vanilla_actors/bitdw/texture.inc.c"

#include "actors/vanilla_actors/bitdw/sliding_platform/model.inc.c"
#include "actors/vanilla_actors/bitdw/seesaw_platform/model.inc.c"
#include "actors/vanilla_actors/bitdw/square_platform/model.inc.c"
#include "actors/vanilla_actors/bitdw/ferris_wheel_axle/model.inc.c"
#include "actors/vanilla_actors/bitdw/ferris_platform/model.inc.c"
#include "actors/vanilla_actors/bitdw/collapsing_stairs_1/model.inc.c"
#include "actors/vanilla_actors/bitdw/collapsing_stairs_2/model.inc.c"
#include "actors/vanilla_actors/bitdw/collapsing_stairs_3/model.inc.c"
#include "actors/vanilla_actors/bitdw/collapsing_stairs_4/model.inc.c"
#include "actors/vanilla_actors/bitdw/collapsing_stairs_5/model.inc.c"
#include "actors/vanilla_actors/bitdw/sliding_platform/collision.inc.c"
#include "actors/vanilla_actors/bitdw/seesaw_platform/collision.inc.c"
#include "actors/vanilla_actors/bitdw/square_platform/collision.inc.c"
#include "actors/vanilla_actors/bitdw/ferris_wheel_axle/collision.inc.c"
#include "actors/vanilla_actors/bitdw/ferris_platform/collision.inc.c"
#include "actors/vanilla_actors/bitdw/collapsing_stairs_1/collision.inc.c"
#include "actors/vanilla_actors/bitdw/collapsing_stairs_2/collision.inc.c"
#include "actors/vanilla_actors/bitdw/collapsing_stairs_3/collision.inc.c"
#include "actors/vanilla_actors/bitdw/collapsing_stairs_4/collision.inc.c"
#include "actors/vanilla_actors/bitdw/collapsing_stairs_5/collision.inc.c"
