COURSE_ACTS(COURSE_BOB, "BOB-OMB BATTLEFIELD",
       "BIG BOB-OMB ON THE SUMMIT"     , "FOOTRACE WITH KOOPA THE QUICK" , "SHOOT TO THE ISLAND IN THE SKY",
       "FIND THE 8 RED COINS"          , "MARIO WINGS TO THE SKY"        , "BEHIND CHAIN CHOMP'S GATE")

COURSE_ACTS(COURSE_WF, "WHOMP'S FORTRESS",
       "CHIP OFF WHOMP'S BLOCK"        , "TO THE TOP OF THE FORTRESS"    , "SHOOT INTO THE WILD BLUE",
       "RED COINS ON THE FLOATING ISLE", "FALL ONTO THE CAGED ISLAND"    , "BLAST AWAY THE WALL")

COURSE_ACTS(COURSE_JRB, "JOLLY ROGER BAY",
       "PLUNDER IN THE SUNKEN SHIP"    , "CAN THE EEL COME OUT TO PLAY?" , "TREASURE OF THE OCEAN CAVE",
       "RED COINS ON THE SHIP AFLOAT"  , "BLAST TO THE STONE PILLAR"     , "THROUGH THE JET STREAM")

COURSE_ACTS(COURSE_CCM, "COOL, COOL MOUNTAIN",
       "SLIP SLIDIN' AWAY"             , "LI'L PENGUIN LOST"             , "BIG PENGUIN RACE",
       "FROSTY SLIDE FOR 8 RED COINS"  , "SNOWMAN'S LOST HIS HEAD"       , "WALL KICKS WILL WORK")

COURSE_ACTS(COURSE_BBH, "BIG BOO'S HAUNT",
       "GO ON A GHOST HUNT"            , "RIDE BIG BOO'S MERRY-GO-ROUND" , "SECRET OF THE HAUNTED BOOKS",
       "SEEK THE 8 RED COINS"          , "BIG BOO'S BALCONY"             , "EYE TO EYE IN THE SECRET ROOM")

COURSE_ACTS(COURSE_HMC, "HAZY MAZE CAVE",
       "SWIMMING BEAST IN THE CAVERN"  , "ELEVATE FOR 8 RED COINS"       , "METAL-HEAD MARIO CAN MOVE!",
       "NAVIGATING THE TOXIC MAZE"     , "A-MAZE-ING EMERGENCY EXIT"     , "WATCH FOR ROLLING ROCKS")

COURSE_ACTS(COURSE_LLL, "LETHAL LAVA LAND",
       "BOIL THE BIG BULLY"            , "BULLY THE BULLIES"             , "8-COIN PUZZLE WITH 15 PIECES",
       "RED-HOT LOG ROLLING"           , "HOT-FOOT-IT INTO THE VOLCANO"  , "ELEVATOR TOUR IN THE VOLCANO")

COURSE_ACTS(COURSE_SSL, "SHIFTING SAND LAND",
       "IN THE TALONS OF THE BIG BIRD" , "SHINING ATOP THE PYRAMID"      , "INSIDE THE ANCIENT PYRAMID",
       "STAND TALL ON THE FOUR PILLARS", "FREE FLYING FOR 8 RED COINS"   , "PYRAMID PUZZLE")

COURSE_ACTS(COURSE_DDD, "DIRE, DIRE DOCKS",
       "BOARD BOWSER'S SUB"            , "CHESTS IN THE CURRENT"         , "POLE-JUMPING FOR RED COINS",
       "THROUGH THE JET STREAM"        , "THE MANTA RAY'S REWARD"        , "COLLECT THE CAPS...")

COURSE_ACTS(COURSE_SL, "SNOWMAN'S LAND",
       "SNOWMAN'S BIG HEAD"            , "CHILL WITH THE BULLY"          , "IN THE DEEP FREEZE",
       "WHIRL FROM THE FREEZING POND"  , "SHELL SHREDDIN' FOR RED COINS" , "INTO THE IGLOO")

COURSE_ACTS(COURSE_WDW, "WET-DRY WORLD",
       "SHOCKING ARROW LIFTS!"         , "TOP O' THE TOWN"               , "SECRETS IN THE SHALLOWS & SKY",
       "EXPRESS ELEVATOR--HURRY UP!"   , "GO TO TOWN FOR RED COINS"      , "QUICK RACE THROUGH DOWNTOWN!")

COURSE_ACTS(COURSE_TTM, "TALL, TALL MOUNTAIN",
       "SCALE THE MOUNTAIN"            , "MYSTERY OF THE MONKEY CAGE"    , "SCARY 'SHROOMS, RED COINS",
       "MYSTERIOUS MOUNTAINSIDE"       , "BREATHTAKING VIEW FROM BRIDGE" , "BLAST TO THE LONELY MUSHROOM")

COURSE_ACTS(COURSE_THI, "TINY-HUGE ISLAND",
       "PLUCK THE PIRANHA FLOWER"      , "THE TIP TOP OF THE HUGE ISLAND", "REMATCH WITH KOOPA THE QUICK",
       "FIVE ITTY BITTY SECRETS"       , "WIGGLER'S RED COINS"           , "MAKE WIGGLER SQUIRM")

COURSE_ACTS(COURSE_TTC, "TICK TOCK CLOCK",
       "ROLL INTO THE CAGE"            , "THE PIT AND THE PENDULUMS"     , "GET A HAND",
       "STOMP ON THE THWOMP"           , "TIMED JUMPS ON MOVING BARS"    , "STOP TIME FOR RED COINS")

COURSE_ACTS(COURSE_RR, "RAINBOW RIDE",
       "CRUISER CROSSING THE RAINBOW"  , "THE BIG HOUSE IN THE SKY"      , "COINS AMASSED IN A MAZE",
       "SWINGIN' IN THE BREEZE"        , "TRICKY TRIANGLES!"             , "SOMEWHERE OVER THE RAINBOW")

SECRET_STAR(COURSE_BITDW, "BOWSER IN THE DARK WORLD")
SECRET_STAR(COURSE_BITFS, "BOWSER IN THE FIRE SEA")
SECRET_STAR(COURSE_BITS, "BOWSER IN THE SKY")
SECRET_STAR(COURSE_PSS, "THE PRINCESS'S SECRET SLIDE")
SECRET_STAR(COURSE_COTMC, "CAVERN OF THE METAL CAP")
SECRET_STAR(COURSE_TOTWC, "TOWER OF THE WING CAP")
SECRET_STAR(COURSE_VCUTM, "VANISH CAP UNDER THE MOAT")
SECRET_STAR(COURSE_WMOTR, "WING MARIO OVER THE RAINBOW")
SECRET_STAR(COURSE_SA, "THE SECRET AQUARIUM")
SECRET_STAR(COURSE_CAKE_END, "")

CASTLE_SECRET_STARS("CASTLE SECRET STARS")

EXTRA_TEXT(0, "ONE OF THE CASTLE'S SECRET STARS!")
EXTRA_TEXT(1, "")
EXTRA_TEXT(2, "")
EXTRA_TEXT(3, "")
EXTRA_TEXT(4, "")
EXTRA_TEXT(5, "")
EXTRA_TEXT(6, "")
