#include <PR/ultratypes.h>
#include <PR/gbi.h>

#include "dialog_ids.h"
#include "surface_terrains.h"
#include "macros.h"
#include "moving_texture_macros.h"
#include "surface_terrains.h"
#include "textures.h"
#include "types.h"

#include "make_const_nonconst.h"

#include "actors/vanilla_actors/bitfs/texture.inc.c"

#include "actors/vanilla_actors/bitfs/elevator/model.inc.c"
#include "actors/vanilla_actors/bitfs/sinking_cage_platform/model.inc.c"
#include "actors/vanilla_actors/bitfs/sinking_cage_pole/model.inc.c"
#include "actors/vanilla_actors/bitfs/tilting_square_platform/model.inc.c"
#include "actors/vanilla_actors/bitfs/tumbling_platform_near/model.inc.c"
#include "actors/vanilla_actors/bitfs/tumbling_platform_far/model.inc.c"
#include "actors/vanilla_actors/bitfs/stretching_platform/1.inc.c"
#include "actors/vanilla_actors/bitfs/stretching_platform/2.inc.c"
#include "actors/vanilla_actors/bitfs/moving_square_platform/model.inc.c"
#include "actors/vanilla_actors/bitfs/sliding_platform/model.inc.c"
#include "actors/vanilla_actors/bitfs/platform_on_track/model.inc.c"
#include "actors/vanilla_actors/bitfs/sinking_platforms/model.inc.c"
#include "actors/vanilla_actors/bitfs/seesaw_platform/model.inc.c"
#include "actors/vanilla_actors/bitfs/elevator/collision.inc.c"
#include "actors/vanilla_actors/bitfs/sinking_cage_platform/collision.inc.c"
#include "actors/vanilla_actors/bitfs/tilting_square_platform/collision.inc.c"
#include "actors/vanilla_actors/bitfs/tumbling_platform_near/collision.inc.c"
#include "actors/vanilla_actors/bitfs/stretching_platform/collision.inc.c"
#include "actors/vanilla_actors/bitfs/moving_square_platform/collision.inc.c"
#include "actors/vanilla_actors/bitfs/sliding_platform/collision.inc.c"
#include "actors/vanilla_actors/bitfs/platform_on_track/collision.inc.c"
#include "actors/vanilla_actors/bitfs/sinking_platforms/collision.inc.c"
#include "actors/vanilla_actors/bitfs/seesaw_platform/collision.inc.c"
