#include <PR/ultratypes.h>
#include <PR/gbi.h>

#include "dialog_ids.h"
#include "surface_terrains.h"
#include "macros.h"
#include "moving_texture_macros.h"
#include "surface_terrains.h"
#include "textures.h"
#include "types.h"

#include "make_const_nonconst.h"

#include "actors/vanilla_actors/ttc/texture.inc.c"

#include "actors/vanilla_actors/ttc/rotating_cube/model.inc.c"
#include "actors/vanilla_actors/ttc/rotating_prism/model.inc.c"
#include "actors/vanilla_actors/ttc/pendulum/model.inc.c"
#include "actors/vanilla_actors/ttc/large_treadmill/model.inc.c"
#include "actors/vanilla_actors/ttc/small_treadmill/model.inc.c"
#include "actors/vanilla_actors/ttc/push_block/model.inc.c"
#include "actors/vanilla_actors/ttc/rotating_hexagon/model.inc.c"
#include "actors/vanilla_actors/ttc/rotating_triangle/model.inc.c"
#include "actors/vanilla_actors/ttc/pit_block/model.inc.c"
#include "actors/vanilla_actors/ttc/pit_block_2/model.inc.c"
#include "actors/vanilla_actors/ttc/elevator_platform/model.inc.c"
#include "actors/vanilla_actors/ttc/clock_hand/model.inc.c"
#include "actors/vanilla_actors/ttc/spinner/model.inc.c"
#include "actors/vanilla_actors/ttc/small_gear/model.inc.c"
#include "actors/vanilla_actors/ttc/large_gear/model.inc.c"

#include "actors/vanilla_actors/ttc/rotating_cube/collision.inc.c"
#include "actors/vanilla_actors/ttc/rotating_prism/collision.inc.c"
#include "actors/vanilla_actors/ttc/pendulum/collision.inc.c"
#include "actors/vanilla_actors/ttc/large_treadmill/collision.inc.c"
#include "actors/vanilla_actors/ttc/small_treadmill/collision.inc.c"
#include "actors/vanilla_actors/ttc/push_block/collision.inc.c"
#include "actors/vanilla_actors/ttc/rotating_hexagon/collision.inc.c"
#include "actors/vanilla_actors/ttc/rotating_triangle/collision.inc.c"
#include "actors/vanilla_actors/ttc/pit_block/collision.inc.c"
#include "actors/vanilla_actors/ttc/pit_block_2/collision.inc.c"
#include "actors/vanilla_actors/ttc/elevator_platform/collision.inc.c"
#include "actors/vanilla_actors/ttc/clock_hand/collision.inc.c"
#include "actors/vanilla_actors/ttc/spinner/collision.inc.c"
