#include "levels/ttc/texture.inc.c"
#include "levels/ttc/areas/1/1/model.inc.c"
#include "levels/ttc/areas/1/2/model.inc.c"
#include "levels/ttc/areas/1/3/model.inc.c"
#include "levels/ttc/areas/1/collision.inc.c"
