COURSE_ACTS(COURSE_BOB, "CAMPO BOB-OMB",
       "EL GRAN BOB-OMB EN LA CIMA"     , "CARRERA CON KOOPA EL VELOZ" , "DISPARA HACIA LA ISLA EN EL CIELO",
       "ENCUENTRA LAS 8 MONEDAS ROJAS"          , "MARIO ALETEA HACIA EL CIELO"        , "DETRÁS DE LA PUERTA DEL CHAIN CHOMP")

COURSE_ACTS(COURSE_WF, " LA FORTALEZA WHOMP",
       "PISOTEA AL WHOMP"        , "HACIA LA CIMA DE LA FORTALEZA"    , "DISPARA HACIA EL CIELO AZUL",
       "MONEDAS ROJAS EN LA ISLA FLOTANTE", "CAE SOBRE LA ISLA ENJAULADA"    , "DESTROZA LA PARED")

COURSE_ACTS(COURSE_JRB, "BAHÍA JOLLY ROGER",
       "SAQUEO EN EL BUQUE HUNDIDO"    , "¿PUEDE SALIR LA ANGUILA A JUGAR?" , "EL TESORO DE LA CUEVA OCEÁNICA",
       "MONEDAS ROJAS EN EL BARCO FLOTANTE"  , "DISPARA AL PILAR DE PIEDRA"     , "A TRAVÉS DE LA CORRIENTE ACUÁTICA")

COURSE_ACTS(COURSE_CCM, "MONTAÑA MUY FRIA",
       "DESLIZÁNDOSE LEJOS"             , "EL PEQUEÑO PINGÚINO PERDIDO"             , "CARRERA CON EL GRAN PINGÚINO",
       "DESLIZAMIENTO HELADO POR 8 MONEDAS ROJAS"  , "EL HOMBRE DE NIEVE HA PERDIDO LA CABEZA"       , "ALTAR DE LA PARED FUNCIONARÁ")

COURSE_ACTS(COURSE_BBH, "GUARIDA DEL GRAN BOO",
       "VE A CAZAR FANTASMAS"            , "ELÉVATE POR 8 MONEDAS ROJAS" , "SECRETO DE LOS LIBROS ENCANTADOS",
       "BUSCA LAS 8 MONEDAS ROJAS"          , "BALCÓN DEL GRAN BOO"             , "OJO A OJO EN LA HABITACIÓN SECRETA")

COURSE_ACTS(COURSE_HMC, "LABERINTO VAGANTE",
       "NADANDO CON LA BESTIA EN LA CAVERNA"  , "ELÉVATE A POR LAS 8 MONEDAS"       , "¡MARIO METÁLICO PUEDE MOVERSE!",
       "NAVEGANDO EL LABERINTO TÓXICO"     , "SALIDA DE EMERGENCIA EN EL LABERINTO"     , "CUIDADO CON LAS ROCAS RODANTES")

COURSE_ACTS(COURSE_LLL, "TIERRA DE LAVA LETAL",
       "FRÍE AL GRAN BULLY"            , "FASTIDIA A LOS BULLIES"             , "PUZZLE DE 8 MONEDAS CON 15 PIEZAS",
       "TRONCO RODANTE, CALIENTE Y ROJO"           , "PON UN PIE EN EL VOLCÁN CALIENTE"  , "TOUR DE ASCENSOR EN EL VOLCÁN")

COURSE_ACTS(COURSE_SSL, "ARENAS CAMBIANTES",
       "EN LOS TALONES DEL AVE GIGANTE" , "BRILLANDO EN LA PUNTA DE LA PIRÁMIDE"      , "DENTRO DE LA PIRÁMIDE ANTIGUA",
       "PISA EN LOS CUATRO PILARES", "VUELO LIBRE POR 8 MONEDAS ROJAS"   , "EL PUZZLE DE LA PIRAMIDE")

COURSE_ACTS(COURSE_DDD, "MUELLE DESOLADO",
       "SÚBETE AL SUBMARINO DE BOWSER"            , "COFRES EN LA CORRIENTE"         , "SALTANDO DE LOS POSTES POR MONEDAS ROJAS",
       "A TRAVÉS DE LA CORRIENTE ACUÁTICA"        , "LA RECOMPENSA DE LA MANTARRAYA"        , "REÚNE LAS GORRAS")

COURSE_ACTS(COURSE_SL, "PAÍS HOMBRE DE NIEVE",
       "LA GRAN CABEZA DEL HOMBRE DE NIEVE"            , "PASANDO EL RATO CON EL BULLY"          , "EN EL FRÍO CONGELANTE",
       "DA VUELTAS DESDE EL ESTANQUE CONGELADO"  , "PATINANDO POR 8 MONEDAS ROJAS" , "DENTRO DEL IGLÚ")

COURSE_ACTS(COURSE_WDW, "MUNDO SECO-MOJADO",
       "¡INCREÍBLES FLECHAS MÓVILES!"         , "EN LO ALTO DEL PUEBLO"               , "SECRETOS EN EL AGUA Y EN EL CIELO",
       "ASCENSORES EXPRÉS. ¡DATE PRISA!"   , "VE AL PUEBLO POR MONEDAS ROJAS"      , "¡CARRERA RÁPIDA A TRAVÉS DEL CENTRO!")

COURSE_ACTS(COURSE_TTM, "MONTAÑA SUBE-SUBE",
       "ESCALA LA MONTAÑA"            , "MISTERIO DE LA JAULA DEL MONO"    , "CHAMPIÑONES TERRORÍFICOS, MONEDAS ROJAS",
       "LADERA MISTERIOSA DE LA MONTAÑA"       , "IMPRESIONANTE VISTA DESDE EL PUENTE" , "DISPARA AL CHAMPIÑÓN SOLITARIO")

COURSE_ACTS(COURSE_THI, "GRAN PEQUEÑA ISLA",
       "ARRANCA LAS PLANTAS PIRAÑA"      , "EN LA CIMA DE LA ENORME ISLA", "REVANCHA CON KOOPA EL VELOZ",
       "CINCO PEQUEÑÍSIMOS SECRETOS"       , "MONEDAS ROJAS DE FLORUGA"           , "HAZ QUE FLORUGA SE RETUERZA")

COURSE_ACTS(COURSE_TTC, "RELOJ TIC-TOC",
       "RUEDA HACIA LA JAULA"            , "EL FOSO Y LOS PÉNDULOS"     , "APÓYATE EN LA MANECILLA",
       "PISOTEA AL THWOMP"           , "SALTOS PRECISOS EN LAS BARRAS MÓVILES"    , "DETÉN EL TIEMPO POR MONEDAS ROJAS")

COURSE_ACTS(COURSE_RR, "CAMINO DEL ARCOÍRIS",
       "CRUCERO QUE CRUZA EL ARCOÍRIS"  , "LA GRAN CASA EN EL CIELO"      , "MONEDAS ACUMULADAS EN UN LABERINTO",
       "BALANCEÁNDOSE EN LA BRISA"        , "¡TRIÁNGULOS PELIAGUDOS!"             , "EN ALGÚN LUGAR MÁS ALLÁ DEL ARCOÍRIS")

SECRET_STAR(COURSE_BITDW, "BOWSER EN EL MUNDO OSCURO")
SECRET_STAR(COURSE_BITFS, "BOWSER EN EL MAR DE FUEGO")
SECRET_STAR(COURSE_BITS, "BOWSER EN EL CIELO")
SECRET_STAR(COURSE_PSS, "EL TOBOGÁN SECRETO DE LA PRINCESA")
SECRET_STAR(COURSE_COTMC, "CAVERNA DE LA GORRA DE METAL")
SECRET_STAR(COURSE_TOTWC, "TORRE DE LA GORRA ALADA")
SECRET_STAR(COURSE_VCUTM, "GORRA INVISIBLE BAJO EL FOSO")
SECRET_STAR(COURSE_WMOTR, "MARIO ALADO SOBRE EL ARCOÍRIS")
SECRET_STAR(COURSE_SA, "EL ACUARIO SECRETO")
SECRET_STAR(COURSE_CAKE_END, "")

CASTLE_SECRET_STARS("ESTRELLAS OCULTAS")

EXTRA_TEXT(0, "¡UNA DE LAS ESTRELLAS OCULTAS!")
EXTRA_TEXT(1, "")
EXTRA_TEXT(2, "")
EXTRA_TEXT(3, "")
EXTRA_TEXT(4, "")
EXTRA_TEXT(5, "")
EXTRA_TEXT(6, "")
