#include <ultra64.h>
#include "sm64.h"
#include "surface_terrains.h"
#include "moving_texture_macros.h"
#include "surface_terrains.h"
#include "textures.h"
#include "dialog_ids.h"

#include "make_const_nonconst.h"

#include "actors_vanilla/rr/texture.inc.c"

#include "actors_vanilla/rr/flying_carpet/model.inc.c"
#include "actors_vanilla/rr/swinging_platform/model.inc.c"
#include "actors_vanilla/rr/rotating_bridge_platform/model.inc.c"
#include "actors_vanilla/rr/cruiser_wing/model.inc.c"
#include "actors_vanilla/rr/octagonal_platform/model.inc.c"
#include "actors_vanilla/rr/sliding_platform/model.inc.c"
#include "actors_vanilla/rr/pyramid_platform/model.inc.c" // Unused
#include "actors_vanilla/rr/elevator_platform/model.inc.c"
#include "actors_vanilla/rr/seesaw_platform/model.inc.c"
#include "actors_vanilla/rr/donut_block/1.inc.c"
#include "actors_vanilla/rr/donut_block/2.inc.c"
#include "actors_vanilla/rr/l_platform/model.inc.c" // also unused
#include "actors_vanilla/rr/tricky_triangles_1/model.inc.c"
#include "actors_vanilla/rr/tricky_triangles_2/model.inc.c"
#include "actors_vanilla/rr/tricky_triangles_3/model.inc.c"
#include "actors_vanilla/rr/tricky_triangles_4/model.inc.c"
#include "actors_vanilla/rr/tricky_triangles_5/model.inc.c"
#include "actors_vanilla/rr/flying_carpet/collision.inc.c"
#include "actors_vanilla/rr/swinging_platform/collision.inc.c"
#include "actors_vanilla/rr/rotating_bridge_platform/collision.inc.c"
#include "actors_vanilla/rr/octagonal_platform/collision.inc.c"
#include "actors_vanilla/rr/sliding_platform/collision.inc.c"
#include "actors_vanilla/rr/pyramid_platform/collision.inc.c"
#include "actors_vanilla/rr/elevator_platform/collision.inc.c"
#include "actors_vanilla/rr/seesaw_platform/collision.inc.c"
#include "actors_vanilla/rr/donut_block/collision.inc.c"
#include "actors_vanilla/rr/l_platform/collision.inc.c"
#include "actors_vanilla/rr/tricky_triangles_1/collision.inc.c"
#include "actors_vanilla/rr/tricky_triangles_2/collision.inc.c"
#include "actors_vanilla/rr/tricky_triangles_3/collision.inc.c"
#include "actors_vanilla/rr/tricky_triangles_4/collision.inc.c"
#include "actors_vanilla/rr/tricky_triangles_5/collision.inc.c"
