#include <ultra64.h>
#include "sm64.h"
#include "surface_terrains.h"
#include "moving_texture_macros.h"
#include "surface_terrains.h"
#include "textures.h"
#include "dialog_ids.h"

#include "make_const_nonconst.h"

#include "actors_vanilla/jrb/header.h"
#include "actors_vanilla/jrb/texture.inc.c"

#include "actors_vanilla/jrb/rock/model.inc.c"
#include "actors_vanilla/jrb/floating_platform/model.inc.c"
#include "actors_vanilla/jrb/sliding_box/model.inc.c"
#include "actors_vanilla/jrb/wooden_ship/model.inc.c"
#include "actors_vanilla/jrb/falling_pillar/model.inc.c"
#include "actors_vanilla/jrb/falling_pillar_base/model.inc.c"
#include "actors_vanilla/jrb/rock/collision.inc.c"
#include "actors_vanilla/jrb/floating_platform/collision.inc.c"
#include "actors_vanilla/jrb/sliding_box/collision.inc.c"
#include "actors_vanilla/jrb/wooden_ship/collision.inc.c"
#include "actors_vanilla/jrb/falling_pillar_base/collision.inc.c"
#include "actors_vanilla/jrb/unused_lid/collision.inc.c"
